// A frozen archive; do not edit by hand and do not regenerate.
//
// What the Python reference implementation `src/limae/hook.py` answered over a
// fixed synthetic corpus, recorded once by `tools/render_diff_cases.py` before
// that implementation and its generator were deleted. `render_tests.rs`
// replays it against this module's port.
//
// Corroborated before the reference was removed by a one-shot sweep at
// `--count 20000`: generating the wider corpus took 24s (25.5 MB) and the port
// reproduced all 20000 cases byte for byte (`cargo test`, exit 0, 62s). That
// reading on its own would not show the sweep could fail, so it has a control
// arm: with the same 20000-case corpus in place, raising `AUTOJUNK` from 200 to
// 300 in `render.rs` turned the same test red (exit 101). The sweep could tell
// the two apart; it was not a large file passing by default.
//
// Nothing can regenerate this file any more, and that is the point rather than
// a shortcoming. Answers recomputed from `render.rs` would be the port's own
// self-portrait: a corpus written from the implementation it checks agrees with
// that implementation whether the port is right or wrong. Only an archive of a
// second, independent implementation can disagree, so freezing is what keeps
// this corpus a reference at all.

/// One before/after pair and the reference implementation's answers for it.
struct Case {
    before: &'static str,
    after: &'static str,
    prose_length: usize,
    trailing: usize,
    flat: &'static str,
    folded: &'static str,
    /// The opcodes as `tag:i1:i2:j1:j2`, separated by spaces.
    opcodes: &'static str,
    changes: &'static str,
}

#[rustfmt::skip]
const CASES: &[Case] = &[
    Case { before: "", after: "", prose_length: 0, trailing: 0, flat: "", folded: "", opcodes: "", changes: "" },
    Case { before: "", after: "新加的一整段", prose_length: 0, trailing: 0, flat: "", folded: "", opcodes: "insert:0:0:0:6", changes: "原 \n改 新加的一整段" },
    Case { before: "原本就有的一段", after: "", prose_length: 7, trailing: 0, flat: "原本就有的一段", folded: "原本就有的一段", opcodes: "delete:0:7:0:0", changes: "原 原本就有的一段\n改" },
    Case { before: "这里有 (注) 一处，正文继续写下去，后面还有别的话。", after: "这里有 「注」 一处，正文继续写下去，后面还有别的话。", prose_length: 25, trailing: 0, flat: "这里有 (注) 一处，正文继续写下去，后面还有别的话。", folded: "这里有(注)一处,正文继续写下去,后面还有别的话.", opcodes: "equal:0:4:0:4 replace:4:5:4:5 equal:5:6:5:6 replace:6:7:6:7 equal:7:27:7:27", changes: "原 这里有 (注) 一处，正文继续写下…\n改 这里有 「注」 一处，正文继续写下…" },
    Case { before: "这里有（注）一处，正文继续写下去，后面还有别的话。", after: "这里有(注)一处，正文继续写下去，后面还有别的话。", prose_length: 25, trailing: 0, flat: "这里有（注）一处，正文继续写下去，后面还有别的话。", folded: "这里有(注)一处,正文继续写下去,后面还有别的话.", opcodes: "equal:0:3:0:3 replace:3:4:3:4 equal:4:5:4:5 replace:5:6:5:6 equal:6:25:6:25", changes: "" },
    Case { before: "一二三四五六七八九十", after: "一二三四五六七八九十", prose_length: 10, trailing: 0, flat: "一二三四五六七八九十", folded: "一二三四五六七八九十", opcodes: "equal:0:10:0:10", changes: "" },
    Case { before: "一二三四五六七八九十甲乙", after: "一二三四五六七八九十丙乙", prose_length: 12, trailing: 0, flat: "一二三四五六七八九十甲乙", folded: "一二三四五六七八九十甲乙", opcodes: "equal:0:10:0:10 replace:10:11:10:11 equal:11:12:11:12", changes: "原 一二三四五六七八九十甲乙\n改 一二三四五六七八九十丙乙" },
    Case { before: "甲一二三四五六七八九十乙", after: "丙一二三四五六七八九十乙", prose_length: 12, trailing: 0, flat: "甲一二三四五六七八九十乙", folded: "甲一二三四五六七八九十乙", opcodes: "replace:0:1:0:1 equal:1:12:1:12", changes: "原 甲一二三四五六七八九十…\n改 丙一二三四五六七八九十…" },
    Case { before: "这一句里有两处要改，前面一处，后面也有一处收尾。", after: "这一句里有两处会改，前面一处，后面也有一处结尾。", prose_length: 24, trailing: 0, flat: "这一句里有两处要改，前面一处，后面也有一处收尾。", folded: "这一句里有两处要改,前面一处,后面也有一处收尾.", opcodes: "equal:0:7:0:7 replace:7:8:7:8 equal:8:21:8:21 replace:21:22:21:22 equal:22:24:22:24", changes: "原 这一句里有两处要改，前面一处，后面也…\n改 这一句里有两处会改，前面一处，后面也…\n\n原 …面一处，后面也有一处收尾。\n改 …面一处，后面也有一处结尾。" },
    Case { before: "紧挨着的甲乙两字", after: "紧挨着的丙丁两字", prose_length: 8, trailing: 0, flat: "紧挨着的甲乙两字", folded: "紧挨着的甲乙两字", opcodes: "equal:0:4:0:4 replace:4:6:4:6 equal:6:8:6:8", changes: "原 紧挨着的甲乙两字\n改 紧挨着的丙丁两字" },
    Case { before: "前面一段话```py\nx = 1\n```\n后面一段话", after: "前面一段话```py\nx = 1\n```\n后面另一段话", prose_length: 13, trailing: 0, flat: "前面一段话```py x = 1 ``` 后面一段话", folded: "前面一段话```pyx=1```后面一段话", opcodes: "equal:0:23:0:23 insert:23:23:23:24 equal:23:26:24:27", changes: "原 …= 1 ``` 后面一段话\n改 …= 1 ``` 后面另一段话" },
    Case { before: "行末有空格 \n下一行\r\n第三行\u{b}第四行\u{1c}第五行", after: "行末有空格\n下一行\r\n第三行\u{b}第四行\u{1c}第五行", prose_length: 17, trailing: 0, flat: "行末有空格 下一行 第三行 第四行 第五行", folded: "行末有空格下一行第三行第四行第五行", opcodes: "equal:0:5:0:5 delete:5:6:5:5 equal:6:23:5:22", changes: "" },
    Case { before: "表情 🙂 也算一个字符，后面继续写。", after: "表情 🙃 也算一个字符，后面继续写。", prose_length: 16, trailing: 0, flat: "表情 🙂 也算一个字符，后面继续写。", folded: "表情🙂也算一个字符,后面继续写.", opcodes: "equal:0:3:0:3 replace:3:4:3:4 equal:4:18:4:18", changes: "原 表情 🙂 也算一个字符，后面…\n改 表情 🙃 也算一个字符，后面…" },
    Case { before: "尾巴上有换行\n\n\n", after: "尾巴上有换行\n", prose_length: 6, trailing: 3, flat: "尾巴上有换行", folded: "尾巴上有换行", opcodes: "equal:0:7:0:7 delete:7:9:7:7", changes: "" },
    Case { before: "~~~\nfenced\n~~~\n只有围栏外算数", after: "~~~\nfenced\n~~~\n只有围栏外的算数", prose_length: 7, trailing: 0, flat: "~~~ fenced ~~~ 只有围栏外算数", folded: "~~~fenced~~~只有围栏外算数", opcodes: "equal:0:20:0:20 insert:20:20:20:21 equal:20:22:21:23", changes: "原 … ~~~ 只有围栏外算数\n改 … ~~~ 只有围栏外的算数" },
    Case { before: "  ```不闭合的围栏\n后面全部不算", after: "  ```不闭合的围栏\n后面也全部不算", prose_length: 0, trailing: 0, flat: "```不闭合的围栏 后面全部不算", folded: "```不闭合的围栏后面全部不算", opcodes: "equal:0:14:0:14 insert:14:14:14:15 equal:14:18:15:19", changes: "原 …`不闭合的围栏 后面全部不算\n改 …`不闭合的围栏 后面也全部不算" },
    Case { before: "空白 与 分隔符\u{1f}都是空白", after: "空白 与 分隔符\u{1f}也是空白", prose_length: 10, trailing: 0, flat: "空白 与 分隔符 都是空白", folded: "空白与分隔符都是空白", opcodes: "equal:0:9:0:9 replace:9:10:9:10 equal:10:13:10:13", changes: "原 空白 与 分隔符 都是空白\n改 空白 与 分隔符 也是空白" },
    Case { before: "b戊。繁ba\n", after: "从繁。繁b", prose_length: 6, trailing: 1, flat: "b戊。繁ba", folded: "b戊.繁ba", opcodes: "replace:0:2:0:2 equal:2:5:2:5 delete:5:7:5:5", changes: "原 b戊。繁ba\n改 从繁。繁b" },
    Case { before: "文字", after: "", prose_length: 2, trailing: 0, flat: "文字", folded: "文字", opcodes: "delete:0:2:0:0", changes: "原 文字\n改" },
    Case { before: "。a）。简aa", after: "。a）。简aa", prose_length: 7, trailing: 0, flat: "。a）。简aa", folded: ".a).简aa", opcodes: "equal:0:7:0:7", changes: "" },
    Case { before: "简b ）（到\n到简到。a。从\n从（简b到）繁\na。a到简b a（） 从a） ,\n从ba（简到aa （简 ）,（b\n从（繁 。简从,从到a简） ）\n。（从\n\n）。。简\n从从a从,\n繁b。  （繁。）\nb,（（b,到\na到\n到。,b \na\n到到,到（（\n简b）简简）。。, a\n）,\n（ 从bb bbab）。）到到aa\nb（aa简）。到）简繁,）\n\n ,繁）b,繁繁） 从,到简b）。（（\n简（b简） ,a ）到简b。 \nb", after: "简b ）（到\n到简到。a。从\n从（简aa\na\na。a到简b a（） 从a） ,\n从ba（简到aa （简 ）,（b\n从（繁 。简从,从到a简） ）\n。（从\n\n）。。简\n从从a从,\n繁b。  （繁。）\nb,（（b,到\na到\n到。,b \na\n到到,到（（\n简b）简简）。。, a\n）,\n（ 从bb bbab）。）到到aaa到从\nb（aa简）。到）简繁,）\n\n ,繁）b,繁繁） 从,到简b）。（（\n 简 简） ,a到简b。 \nb", prose_length: 168, trailing: 0, flat: "简b ）（到 到简到。a。从 从（简b到）繁 a。a到简b a（） 从a） , 从ba（简到aa （简 ）,（b 从（繁 。简从,从到a简） ） 。（从 ）。。简 从从a从, 繁b。 （繁。） b,（（b,到 a到 到。,b a 到到,到（（ 简b）简简）。。, a ）, （ 从bb bbab）。）到到aa b（aa简）。到）简繁,） ,繁）b,繁繁） 从,到简b）。（（ 简（b简） ,a ）到简b。 b", folded: "简b)(到到简到.a.从从(简b到)繁a.a到简ba()从a),从ba(简到aa(简),(b从(繁.简从,从到a简)).(从)..简从从a从,繁b.(繁.)b,((b,到a到到.,ba到到,到((简b)简简)..,a),(从bbbbab).)到到aab(aa简).到)简繁,),繁)b,繁繁)从,到简b).((简(b简),a)到简b.b", opcodes: "equal:0:18:0:18 replace:18:210:18:211", changes: "原 …简到。a。从 从（简b到）繁 a。a到简b a（） 从a） , 从ba（简到aa （简 ）,（b 从（繁 。简从,从到a简） ） 。（从 ）。。简 从从a从, 繁b。 （繁。） b,（（b,到 a到 到。,b a 到到,到（（ 简b）简简）。。, a ）, （ 从bb bbab）。）到到aa b（aa简）。到）简繁,） ,繁）b,繁繁） 从,到简b）。（（ 简（b简） ,a ）到简b。 b\n改 …简到。a。从 从（简aa a a。a到简b a（） 从a） , 从ba（简到aa （简 ）,（b 从（繁 。简从,从到a简） ） 。（从 ）。。简 从从a从, 繁b。 （繁。） b,（（b,到 a到 到。,b a 到到,到（（ 简b）简简）。。, a ）, （ 从bb bbab）。）到到aaa到从 b（aa简）。到）简繁,） ,繁）b,繁繁） 从,到简b）。（（ 简 简） ,a到简b。 b" },
    Case { before: "value。。是。the很短是 这一段很短很短这一段", after: "是。己简（丁。the己己丁,己很短是 ）。。到戊戊短这一段", prose_length: 25, trailing: 0, flat: "value。。是。the很短是 这一段很短很短这一段", folded: "value..是.the很短是这一段很短很短这一段", opcodes: "replace:0:5:0:1 equal:5:6:1:2 replace:6:8:2:6 equal:8:12:6:10 insert:12:12:10:15 equal:12:16:15:19 replace:16:22:19:25 equal:22:26:25:29", changes: "原 value。。是。the很短是 这一段很短很短这一段\n改 是。己简（丁。the己己丁,己很短是 ）。。到戊戊短这一段" },
    Case { before: "  b a）简。\n 繁（,简（繁繁简b）））从）,。（（ 。））,,到繁b,简繁", after: "  b a）简。\n 从a。b,繁繁简b））b）从（）,,到繁b,简繁", prose_length: 34, trailing: 0, flat: "b a）简。 繁（,简（繁繁简b）））从）,。（（ 。））,,到繁b,简繁", folded: "ba)简.繁(,简(繁繁简b)))从),.((.)),,到繁b,简繁", opcodes: "equal:0:10:0:10 replace:10:12:10:14 equal:12:13:14:15 delete:13:15:15:15 equal:15:21:15:21 insert:21:21:21:22 equal:21:23:22:24 delete:23:26:24:24 equal:26:27:24:25 delete:27:31:25:25 equal:31:40:25:34", changes: "原 b a）简。 繁（,简（繁繁简b）））从）,。（（ 。））,,到繁b,简繁\n改 b a）简。 从a。b,繁繁简b））b）从（）,,到繁b,简繁" },
    Case { before: "从到 b\na从, a从a,到 b\na\n繁\nb 简）a到）到到）（。到到 简 \n（ 。繁繁繁\n简从\n。。）繁\nb\n\n。到,\n从。ba从,（,简从从 b）b繁（到,到。a到简简简从从繁）简 b）到。\n,从。（从 简简（繁从。 从繁b b从繁从到繁 a到） 到到。 从到\nb, 简,简（。从到,简（。\n到ba,到aaba到到,繁从,,b,ab简简从到\n。（。 ,从（。）。到,）bb）（）a,）a繁ab。从b", after: "从到 b\na从, a从a,到 b\na\n繁\nb 简）a到）到到）（。到到 简 \n（ 。繁繁繁\n简从\n。。）繁\nb\n\n。到,\n从。ba从,（,简从从 b）b繁（到,到。a到简简简从从繁）简 b）到。\n,从。（从 简简（繁从。 从繁b b从繁从到繁 a到） 到到。 从到\nb, 简,简（。从到,简（。\n到ba,到aaba到到,繁从,,b,ab简简从到\n。（。 ,从（。）。到,）bb）（）a,）a繁ab。从b", prose_length: 169, trailing: 0, flat: "从到 b a从, a从a,到 b a 繁 b 简）a到）到到）（。到到 简 （ 。繁繁繁 简从 。。）繁 b 。到, 从。ba从,（,简从从 b）b繁（到,到。a到简简简从从繁）简 b）到。 ,从。（从 简简（繁从。 从繁b b从繁从到繁 a到） 到到。 从到 b, 简,简（。从到,简（。 到ba,到aaba到到,繁从,,b,ab简简从到 。（。 ,从（。）。到,）bb）（）a,）a繁ab。从b", folded: "从到ba从,a从a,到ba繁b简)a到)到到)(.到到简(.繁繁繁简从..)繁b.到,从.ba从,(,简从从b)b繁(到,到.a到简简简从从繁)简b)到.,从.(从简简(繁从.从繁bb从繁从到繁a到)到到.从到b,简,简(.从到,简(.到ba,到aaba到到,繁从,,b,ab简简从到.(.,从(.).到,)bb)()a,)a繁ab.从b", opcodes: "equal:0:201:0:201", changes: "" },
    Case { before: "。b", after: "。aa（", prose_length: 2, trailing: 0, flat: "。b", folded: ".b", opcodes: "equal:0:1:0:1 replace:1:2:1:4", changes: "原 。b\n改 。aa（" },
    Case { before: "the", after: "the", prose_length: 3, trailing: 0, flat: "the", folded: "the", opcodes: "equal:0:3:0:3", changes: "" },
    Case { before: "。value 合成的是。 ，这一段valuethe文字文字\n \n the，value合成的 value文字。是，value合成的很短the\n很短value\n很短value，\n。。，这一段合成的thevalue很短  合成的很短很短很短这一段\n是很短是很短这一段是\nvalue\n这一段是value ，。", after: "。value 合成的是。 ，这一段valuethe文字文字\n \n the，value合成的 value文字。是，value合成的很短the\n很短value短value，\n。。，这一段合成的thevalue很短  合成的很短很短很繁繁到段\n是很短是很短这一段是\nvalue\n这一段是value ，。", prose_length: 134, trailing: 0, flat: "。value 合成的是。 ，这一段valuethe文字文字 the，value合成的 value文字。是，value合成的很短the 很短value 很短value， 。。，这一段合成的thevalue很短 合成的很短很短很短这一段 是很短是很短这一段是 value 这一段是value ，。", folded: ".value合成的是.,这一段valuethe文字文字the,value合成的value文字.是,value合成的很短the很短value很短value,..,这一段合成的thevalue很短合成的很短很短很短这一段是很短是很短这一段是value这一段是value,.", opcodes: "equal:0:77:0:77 delete:77:79:77:77 equal:79:116:77:114 replace:116:119:114:117 equal:119:150:117:148", changes: "原 …he 很短value 很短value， 。。…\n改 …he 很短value短value， 。。…\n\n原 … 合成的很短很短很短这一段 是很短是很短这一…\n改 … 合成的很短很短很繁繁到段 是很短是很短这一…" },
    Case { before: "", after: "", prose_length: 0, trailing: 0, flat: "", folded: "", opcodes: "", changes: "" },
    Case { before: "己", after: " 丁", prose_length: 1, trailing: 0, flat: "己", folded: "己", opcodes: "replace:0:1:0:2", changes: "原 己\n改 丁" },
    Case { before: "从繁b繁,a（（从繁）从a繁从, a,到a  从简）,到（ （aa繁）（简到 简", after: "从繁b繁,繁）从a繁从, a,到a  从简）,到（ （aa繁）（简到 简", prose_length: 35, trailing: 0, flat: "从繁b繁,a（（从繁）从a繁从, a,到a 从简）,到（ （aa繁）（简到 简", folded: "从繁b繁,a((从繁)从a繁从,a,到a从简),到((aa繁)(简到简", opcodes: "equal:0:5:0:5 delete:5:9:5:5 equal:9:40:5:36", changes: "原 从繁b繁,a（（从繁）从a繁从, a,…\n改 从繁b繁,繁）从a繁从, a,…" },
    Case { before: "简到从）ba a）a繁 b （  baa简 （到繁a（\n繁（从a 简ba到,a 繁\n。（繁a\n繁繁从 ,\na） 简\n。a。 ,,\na,到从简 简。）（b繁简 a,（到）,\n简\n,繁到繁（（））ab到到简,到a从（到a）到繁简简b繁到 ,b到bb b,。 b到（到ba（,简（到简简 b从到, a 从从从b简繁从）b）a（从\n繁到到）b到 ）（）到到简,繁 \n。bba到,简, \n））（（到到a。简 简（到从\n从b  简）。,繁（）bb。b从\n到a简 到简 简到）,。）从a（b到\n 繁繁a。）繁\n\n繁。\n）从简）（到\n简", after: "简到从）ba a）a繁 b （  baa简 （到繁a（\n繁（从a 简ba到,a 繁\n。（繁a\n繁繁从 ,\na） 简\n。a。 ,,\na,到从简 简。）（b繁简 a,（到）,\n简\n,繁到繁（（））ab到到简,到a从（到a）到繁简简b繁到 ,b到bb b,。 b到（到ba（,简（到简简 b从到, a 从从从b简繁从）b）a（从\n繁到到）b到 ）（）到到简,繁 \n。bba到,简, \n））（（到到a。简 简（到从\n从b  简）。,繁（）bb。b从\n到a简从到简 简到）,。）从a（b到\n 繁繁a。）繁\n\n繁。\n）从简简（到\n简", prose_length: 214, trailing: 0, flat: "简到从）ba a）a繁 b （ baa简 （到繁a（ 繁（从a 简ba到,a 繁 。（繁a 繁繁从 , a） 简 。a。 ,, a,到从简 简。）（b繁简 a,（到）, 简 ,繁到繁（（））ab到到简,到a从（到a）到繁简简b繁到 ,b到bb b,。 b到（到ba（,简（到简简 b从到, a 从从从b简繁从）b）a（从 繁到到）b到 ）（）到到简,繁 。bba到,简, ））（（到到a。简 简（到从 从b 简）。,繁（）bb。b从 到a简 到简 简到）,。）从a（b到 繁繁a。）繁 繁。 ）从简）（到 简", folded: "简到从)baa)a繁b(baa简(到繁a(繁(从a简ba到,a繁.(繁a繁繁从,a)简.a.,,a,到从简简.)(b繁简a,(到),简,繁到繁(())ab到到简,到a从(到a)到繁简简b繁到,b到bbb,.b到(到ba(,简(到简简b从到,a从从从b简繁从)b)a(从繁到到)b到)()到到简,繁.bba到,简,))((到到a.简简(到从从b简).,繁()bb.b从到a简到简简到),.)从a(b到繁繁a.)繁繁.)从简)(到简", opcodes: "equal:0:224:0:224 replace:224:260:224:260", changes: "原 …）bb。b从 到a简 到简 简到）,。）从a（b到 繁繁a。）繁 繁。 ）从简）（到 简\n改 …）bb。b从 到a简从到简 简到）,。）从a（b到 繁繁a。）繁 繁。 ）从简简（到 简" },
    Case { before: "文字\n\n合成的是\nvalue这一段value很短\n文字。 ，value 这一段是the这一段 这一段\n合成的是是文字这一段\nvalue文字合成的，， 。。很短文字 文字the\n，文字\n，文字\n文字很短是  ，这一段这一段，，the是。这一段这一段是\nvaluevalue ", after: "文字\n\n合成的是\nvalue这一段value很短\n文字。 ，value （）繁简这一段是the这一段 这一段\n合成的是是文字这一段\nvalue文字合成的，， 。。很短文字 文字the\n，文字\n，文字\n文字很短是  ，这）（一段这一段，，the是。这一段这一段是\nvaluevalue ", prose_length: 118, trailing: 0, flat: "文字 合成的是 value这一段value很短 文字。 ，value 这一段是the这一段 这一段 合成的是是文字这一段 value文字合成的，， 。。很短文字 文字the ，文字 ，文字 文字很短是 ，这一段这一段，，the是。这一段这一段是 valuevalue", folded: "文字合成的是value这一段value很短文字.,value这一段是the这一段这一段合成的是是文字这一段value文字合成的,,..很短文字文字the,文字,文字文字很短是,这一段这一段,,the是.这一段这一段是valuevalue", opcodes: "equal:0:36:0:36 insert:36:36:36:40 equal:36:105:40:109 insert:105:105:109:111 equal:105:136:111:142", changes: "原 …字。 ，value 这一段是the这一段…\n改 …字。 ，value （）繁简这一段是the这一段…\n\n原 … 文字很短是 ，这一段这一段，，the…\n改 … 文字很短是 ，这）（一段这一段，，the…" },
    Case { before: ",,。,从,繁从从 ）\n从aa繁简ba。a简 从繁  简\n）aa）a（,从 b。从a（繁 从a繁abb,,,到b\n,从到ab,繁 简简b ）\n（从繁简繁。。,繁）,繁从）（aa\n\n （b\n,。（\n）从繁简）） \n从\n）到（到b\n繁\n简）从从）（从 \n到。从）a \n\n）,,a（从）（。ab。 ）a从） ,a,,到到繁。（\n到 。。从简从繁a。简繁到繁 ）\n简 到aa b（\nb）（b\n,从\n,到从（", after: ",,。,从,繁从从繁简ba。a简 从繁  简\n）aa）a（,从 b。从a（繁 从a繁abb,,,到b\n,从到ab,繁 简简b ）\n（从繁简繁。。,繁）,繁从）（aa\n\n （b\n,。（\n）从繁简）） \n从\n）到（到b\n繁\n简）从从）（从 \n到。从）a \n\n）,,a（从）（。ab。 ）a从） ,a,,到到繁。（\n到 。。从简从繁a。简繁到繁 ）\n简 到a\n）b（\nb）（b\n,从\n,到从（", prose_length: 161, trailing: 0, flat: ",,。,从,繁从从 ） 从aa繁简ba。a简 从繁 简 ）aa）a（,从 b。从a（繁 从a繁abb,,,到b ,从到ab,繁 简简b ） （从繁简繁。。,繁）,繁从）（aa （b ,。（ ）从繁简）） 从 ）到（到b 繁 简）从从）（从 到。从）a ）,,a（从）（。ab。 ）a从） ,a,,到到繁。（ 到 。。从简从繁a。简繁到繁 ） 简 到aa b（ b）（b ,从 ,到从（", folded: ",,.,从,繁从从)从aa繁简ba.a简从繁简)aa)a(,从b.从a(繁从a繁abb,,,到b,从到ab,繁简简b)(从繁简繁..,繁),繁从)(aa(b,.()从繁简))从)到(到b繁简)从从)(从到.从)a),,a(从)(.ab.)a从),a,,到到繁.(到..从简从繁a.简繁到繁)简到aab(b)(b,从,到从(", opcodes: "equal:0:9:0:9 delete:9:15:9:9 equal:15:182:9:176 replace:182:184:176:178 equal:184:199:178:193", changes: "原 ,,。,从,繁从从 ） 从aa繁简ba。a简 从繁…\n改 ,,。,从,繁从从繁简ba。a简 从繁…\n\n原 …繁到繁 ） 简 到aa b（ b）（b ,从…\n改 …繁到繁 ） 简 到a ）b（ b）（b ,从…" },
    Case { before: "value", after: "value", prose_length: 5, trailing: 0, flat: "value", folded: "value", opcodes: "equal:0:5:0:5", changes: "" },
    Case { before: "这一段文字value。 ，是value很短，是\n是。thevalue这一段这一段 这一段很短这一段是合成的很短是value\n ，是文字合成的 \n 文字合成的很短文字", after: ",这一段文字value。 ，是value很短，是\nevalue这一段这一段 这一段很短这一段是合成的很短是value\n ，是文字合成的 \n 文字合成的很短文字", prose_length: 74, trailing: 0, flat: "这一段文字value。 ，是value很短，是 是。thevalue这一段这一段 这一段很短这一段是合成的很短是value ，是文字合成的 文字合成的很短文字", folded: "这一段文字value.,是value很短,是是.thevalue这一段这一段这一段很短这一段是合成的很短是value,是文字合成的文字合成的很短文字", opcodes: "insert:0:0:0:1 equal:0:24:1:25 delete:24:28:25:25 equal:28:82:25:79", changes: "原 这一段文字value…\n改 ,这一段文字value…\n\n原 …value很短，是 是。thevalue这一段这…\n改 …value很短，是 evalue这一段这…" },
    Case { before: "繁b", after: "简,到 b", prose_length: 2, trailing: 0, flat: "繁b", folded: "繁b", opcodes: "replace:0:1:0:4 equal:1:2:4:5", changes: "原 繁b\n改 简,到 b" },
    Case { before: " ，the这一段\nthe文字很短合成的这一段\n\n是是valuethe是这一段 ，这一段这一段这一段，这一段很短合成的。\n很短是合成的合成的the。是这一段这一段，the是是 value文字很短合成的， \n这一段合成的the很短。合成的，the，文字合成的\n合成的valuevalue文字", after: " ，the这一段\nthe文字很短合成的这一段\n\n是是val是这一段 ，这一段这一段这一段，这一段很短合成的。\n,繁很短是合成的合成的the。是这一段这一段，the是是 value文字很短合成的， \n这一段合成的the很短。合成的，the，文字合成的\n合成的valuevalue文字", prose_length: 133, trailing: 0, flat: "，the这一段 the文字很短合成的这一段 是是valuethe是这一段 ，这一段这一段这一段，这一段很短合成的。 很短是合成的合成的the。是这一段这一段，the是是 value文字很短合成的， 这一段合成的the很短。合成的，the，文字合成的 合成的valuevalue文字", folded: ",the这一段the文字很短合成的这一段是是valuethe是这一段,这一段这一段这一段,这一段很短合成的.很短是合成的合成的the.是这一段这一段,the是是value文字很短合成的,这一段合成的the很短.合成的,the,文字合成的合成的valuevalue文字", opcodes: "equal:0:29:0:29 delete:29:34:29:29 equal:34:60:29:55 insert:60:60:55:57 equal:60:143:57:140", changes: "原 …这一段 是是valuethe是这一段 ，这一段这…\n改 …这一段 是是val是这一段 ，这一段这…\n\n原 …这一段很短合成的。 很短是合成的合成的t…\n改 …这一段很短合成的。 ,繁很短是合成的合成的t…" },
    Case { before: "很短，", after: "很短，", prose_length: 3, trailing: 0, flat: "很短，", folded: "很短,", opcodes: "equal:0:3:0:3", changes: "" },
    Case { before: "\n。合成的，文字thethe合成的the。合成的\n\n是the。\n 文字是the\n。\n文字 。是 是\n合成的合成的文字the，很短很短是value，\n文字是合成的合成的，很短。文字这一段是文字。合成的。\n。这一段\nvaluethe。 是，", after: "\n。合成的，文字thethe的the。合成的\n\n戊\na从简是the。\n 文字是the\n。\n文字 。是 是\n合成的合成的文字繁丁到（）the，很短很短是value，\n文字是合成的合成的，很短。文字这一段是文字。合成的。\n。这一段\nvaluethe。 是，", prose_length: 104, trailing: 0, flat: "。合成的，文字thethe合成的the。合成的 是the。 文字是the 。 文字 。是 是 合成的合成的文字the，很短很短是value， 文字是合成的合成的，很短。文字这一段是文字。合成的。 。这一段 valuethe。 是，", folded: ".合成的,文字thethe合成的the.合成的是the.文字是the.文字.是是合成的合成的文字the,很短很短是value,文字是合成的合成的,很短.文字这一段是文字.合成的..这一段valuethe.是,", opcodes: "equal:0:14:0:14 delete:14:16:14:14 equal:16:26:14:24 insert:26:26:24:29 equal:26:58:29:61 insert:58:58:61:66 equal:58:118:66:126", changes: "原 …的，文字thethe合成的the。合成的 …\n改 …的，文字thethe的the。合成的 …\n\n原 …的the。合成的 是the。 文字是…\n改 …的the。合成的 戊 a从简是the。 文字是…\n\n原 …是 合成的合成的文字the，很短很短是v…\n改 …是 合成的合成的文字繁丁到（）the，很短很短是v…" },
    Case { before: "ba简从繁）到到到从\n,aab 繁从到） a \n（（\n。））\n。（ 从 b简简a繁简简 到。 \na b简繁,从。 到。简 简（,简从a。简\n 。从从（从简（（ \n从从\n。 （简。）到）ab）bb从从繁从到a（（a（简。繁。繁到到繁。从ba\nb）。（\n从,繁）到a到）（b从到,从b繁。（,ba ）简。（繁从 从,繁b从,繁繁。（）a从简简简a）繁） ）b（。从\n （到到从（。繁b,（\n简。从）（ 。b从从b繁（\n （（a从a。从从（到）到简到。。 繁a从）简b,）（繁（从到从从。简\n从到 到到从。 从。,。到  a简", after: "ba简从繁）到到到从\n,aab 繁从到） a \n（（\n。））\n。（ 从 b简简a繁简简 到。 \na b简繁,从。 到。简 简（,简从a。简\n 。从从（从简（（ \n从从\n。 （简。）到）ab）bb从从繁从到a（（a（简。繁。繁到到繁。从b从,繁）到a到）（b从到,从b繁。（,ba ）简。（繁从 从,繁b从,繁繁。（）a从简简简a）繁） ）b（。从\n （到到从（。繁b,（\n简。从）（ 。b从从b繁（\n （（a从a。从从（）到简到。。 繁a从）简b,）（繁（从到从从。简\n从到 到到从。 从。,。到  a简", prose_length: 222, trailing: 0, flat: "ba简从繁）到到到从 ,aab 繁从到） a （（ 。）） 。（ 从 b简简a繁简简 到。 a b简繁,从。 到。简 简（,简从a。简 。从从（从简（（ 从从 。 （简。）到）ab）bb从从繁从到a（（a（简。繁。繁到到繁。从ba b）。（ 从,繁）到a到）（b从到,从b繁。（,ba ）简。（繁从 从,繁b从,繁繁。（）a从简简简a）繁） ）b（。从 （到到从（。繁b,（ 简。从）（ 。b从从b繁（ （（a从a。从从（到）到简到。。 繁a从）简b,）（繁（从到从从。简 从到 到到从。 从。,。到 a简", folded: "ba简从繁)到到到从,aab繁从到)a((.)).(从b简简a繁简简到.ab简繁,从.到.简简(,简从a.简.从从(从简((从从.(简.)到)ab)bb从从繁从到a((a(简.繁.繁到到繁.从bab).(从,繁)到a到)(b从到,从b繁.(,ba)简.(繁从从,繁b从,繁繁.()a从简简简a)繁))b(.从(到到从(.繁b,(简.从)(.b从从b繁(((a从a.从从(到)到简到..繁a从)简b,)(繁(从到从从.简从到到到从.从.,.到a简", opcodes: "equal:0:118:0:118 replace:118:260:118:252", changes: "原 …。繁。繁到到繁。从ba b）。（ 从,繁）到a到）（b从到,从b繁。（,ba ）简。（繁从 从,繁b从,繁繁。（）a从简简简a）繁） ）b（。从 （到到从（。繁b,（ 简。从）（ 。b从从b繁（ （（a从a。从从（到）到简到。。 繁a从）简b,）（繁（从到从从。简 从到 到到从。 从。,。到 a简\n改 …。繁。繁到到繁。从b从,繁）到a到）（b从到,从b繁。（,ba ）简。（繁从 从,繁b从,繁繁。（）a从简简简a）繁） ）b（。从 （到到从（。繁b,（ 简。从）（ 。b从从b繁（ （（a从a。从从（）到简到。。 繁a从）简b,）（繁（从到从从。简 从到 到到从。 从。,。到 a简" },
    Case { before: "文字\n\n是thevalue。文字是the，，。the文字the，文字the。这一段很短合成的value合成的很短很短，the这一段是这一段是。 value文字很短很短\n", after: "文字\n\n是thevalue。文字是the，，。the文字the，文字the。这一段很短合成的value合成的很短很短，the这一段是这一段是。 value文字从到。 \n", prose_length: 80, trailing: 1, flat: "文字 是thevalue。文字是the，，。the文字the，文字the。这一段很短合成的value合成的很短很短，the这一段是这一段是。 value文字很短很短", folded: "文字是thevalue.文字是the,,.the文字the,文字the.这一段很短合成的value合成的很短很短,the这一段是这一段是.value文字很短很短", opcodes: "equal:0:79:0:79 replace:79:83:79:83 equal:83:84:83:84", changes: "原 …是。 value文字很短很短\n改 …是。 value文字从到。" },
    Case { before: "从b到简a\n。到）\n到简a,。。  繁（b到b,, \n繁简 繁到）b 到 简到到（从到 繁ab到。（a到 繁,）繁ba。 \n简）从,。繁\n简到 b。繁ba（简简简从繁）从到。从 ba（繁,到\n从b繁,（\n到b\na）从。,（,b（繁。从\n从 繁到从 简\n 。bba,到（\n）。b,简繁繁。繁）\n,\n）到\n（a\n从b）（。到繁。到,ba到简b bbbba。。到 \n（\n（繁。,（简ab,到）到简繁。 ", after: "从b到简a\n。到）\n到简a,。。  繁（b到b,, \n繁简 繁到）b 到 简到到（从到 繁ab到。（a到 繁,）繁ba。 \n简）从,。繁\n简到 b。繁ba（简简简从繁）从到。从 ba（繁,到\n从b繁,（\n到b\na）从。,（,b（繁。从\n从 繁到从 简\n 。bba,到（\n）。b,简繁繁。繁）\n,\n）到\n（a\n从b）（。到繁。到,ba到简b bbbba。。到 \n（\n（繁。,（简ab,到）到简繁。 ", prose_length: 164, trailing: 0, flat: "从b到简a 。到） 到简a,。。 繁（b到b,, 繁简 繁到）b 到 简到到（从到 繁ab到。（a到 繁,）繁ba。 简）从,。繁 简到 b。繁ba（简简简从繁）从到。从 ba（繁,到 从b繁,（ 到b a）从。,（,b（繁。从 从 繁到从 简 。bba,到（ ）。b,简繁繁。繁） , ）到 （a 从b）（。到繁。到,ba到简b bbbba。。到 （ （繁。,（简ab,到）到简繁。", folded: "从b到简a.到)到简a,..繁(b到b,,繁简繁到)b到简到到(从到繁ab到.(a到繁,)繁ba.简)从,.繁简到b.繁ba(简简简从繁)从到.从ba(繁,到从b繁,(到ba)从.,(,b(繁.从从繁到从简.bba,到().b,简繁繁.繁),)到(a从b)(.到繁.到,ba到简bbbbba..到((繁.,(简ab,到)到简繁.", opcodes: "equal:0:198:0:198", changes: "" },
    Case { before: "很短是", after: "很b是", prose_length: 3, trailing: 0, flat: "很短是", folded: "很短是", opcodes: "equal:0:1:0:1 replace:1:2:1:2 equal:2:3:2:3", changes: "原 很短是\n改 很b是" },
    Case { before: "a到从 b己）己\n。到繁a到简从,繁。b丁a丙\n戊。繁（ 戊从丙（ \n （\n。b", after: "a到从 b己）己\n。到繁a到简从,繁。b丁a丙\n戊。繁（ 戊从丙（ \n （\n。b", prose_length: 32, trailing: 0, flat: "a到从 b己）己 。到繁a到简从,繁。b丁a丙 戊。繁（ 戊从丙（ （ 。b", folded: "a到从b己)己.到繁a到简从,繁.b丁a丙戊.繁(戊从丙((.b", opcodes: "equal:0:40:0:40", changes: "" },
    Case { before: "是the  文字。\n。。很短  value是合成的合成的\n文字value   这一段value合成的thevalue是。合成的value，value是是很短\n是合成的 这一段value文字这一段这一段，。合成的\nvaluevaluethe是value\n这一段。合成的 这一段这一段很短，valuethe，这一段", after: "是the  文字。\n。。很短  value是合成的合成的\n文字value   这一段value合成繁。b的thevalue是。合成的value，value是是很短\n是合成的 这一段value文字这一段这一段，。合成的\nvaluevaluethe是value\n这一段。合成的 这段很短，valu一段", prose_length: 141, trailing: 0, flat: "是the 文字。 。。很短 value是合成的合成的 文字value 这一段value合成的thevalue是。合成的value，value是是很短 是合成的 这一段value文字这一段这一段，。合成的 valuevaluethe是value 这一段。合成的 这一段这一段很短，valuethe，这一段", folded: "是the文字...很短value是合成的合成的文字value这一段value合成的thevalue是.合成的value,value是是很短是合成的这一段value文字这一段这一段,.合成的valuevaluethe是value这一段.合成的这一段这一段很短,valuethe,这一段", opcodes: "equal:0:49:0:49 insert:49:49:49:52 equal:49:135:52:138 delete:135:139:138:138 equal:139:147:138:146 delete:147:153:146:146 equal:153:155:146:148", changes: "原 …这一段value合成的thevalue是…\n改 …这一段value合成繁。b的thevalue是…\n\n原 … 这一段。合成的 这一段这一段很短，valuet…\n改 … 这一段。合成的 这段很短，valuet…\n\n原 …这一段很短，valuethe，这一段\n改 …这一段很短，valu一段" },
    Case { before: "简 ）繁）己丁,\n。b）a从己 繁,戊从,丙繁从简简。）））b到b丙）丁a。,, ,））,丁\n丁\n。。,\n）从丁到丁b丙a戊简到己丁戊a,a（简a到a己。）从。  到繁。戊（己。（）丁\n丙b从己  ,\n戊a,a到丁戊（b\n己丙丙从。 。）\n）繁丙\n（b到己）繁aa戊简戊。简丁a戊b戊丁到b（繁（（戊（。从aa丙（己（丁b简b简 丙b简从（（从a（,到  从   （。\nb）戊（）丙简戊）从）简\n（。）", after: "简 ）繁）己丁,\n。b）a从己 繁,戊从,丙繁从简简。）））b）己丁a到b丙）丁a。,, ,））,丁\n丁\n。。,\n）从丁到丁b丙a戊简到己丁戊a,a（简a到a己。）从。  到繁。戊（己。（）丁\n丙b从己  ,\n戊a,a到丁戊（b\n己丙丙从。 。）\n）繁丙\n（b到己）繁aa戊简戊。简丁a戊b戊丁到b（繁（（戊（。从aa丙（己（丁b简b简 丙b简从（（从a（,到  从   （。\nb）戊（）丙简戊）从）简\n（。）", prose_length: 176, trailing: 0, flat: "简 ）繁）己丁, 。b）a从己 繁,戊从,丙繁从简简。）））b到b丙）丁a。,, ,））,丁 丁 。。, ）从丁到丁b丙a戊简到己丁戊a,a（简a到a己。）从。 到繁。戊（己。（）丁 丙b从己 , 戊a,a到丁戊（b 己丙丙从。 。） ）繁丙 （b到己）繁aa戊简戊。简丁a戊b戊丁到b（繁（（戊（。从aa丙（己（丁b简b简 丙b简从（（从a（,到 从 （。 b）戊（）丙简戊）从）简 （。）", folded: "简)繁)己丁,.b)a从己繁,戊从,丙繁从简简.)))b到b丙)丁a.,,,)),丁丁..,)从丁到丁b丙a戊简到己丁戊a,a(简a到a己.)从.到繁.戊(己.()丁丙b从己,戊a,a到丁戊(b己丙丙从..))繁丙(b到己)繁aa戊简戊.简丁a戊b戊丁到b(繁((戊(.从aa丙(己(丁b简b简丙b简从((从a(,到从(.b)戊()丙简戊)从)简(.)", opcodes: "equal:0:31:0:31 replace:31:201:31:205", changes: "原 …丙繁从简简。）））b到b丙）丁a。,, ,））,丁 丁 。。, ）从丁到丁b丙a戊简到己丁戊a,a（简a到a己。）从。 到繁。戊（己。（）丁 丙b从己 , 戊a,a到丁戊（b 己丙丙从。 。） ）繁丙 （b到己）繁aa戊简戊。简丁a戊b戊丁到b（繁（（戊（。从aa丙（己（丁b简b简 丙b简从（（从a（,到 从 （。 b）戊（）丙简戊）从）简 （。）\n改 …丙繁从简简。）））b）己丁a到b丙）丁a。,, ,））,丁 丁 。。, ）从丁到丁b丙a戊简到己丁戊a,a（简a到a己。）从。 到繁。戊（己。（）丁 丙b从己 , 戊a,a到丁戊（b 己丙丙从。 。） ）繁丙 （b到己）繁aa戊简戊。简丁a戊b戊丁到b（繁（（戊（。从aa丙（己（丁b简b简 丙b简从（（从a（,到 从 （。 b）戊（）丙简戊）从）简 （。）" },
    Case { before: "文字", after: "文）", prose_length: 2, trailing: 0, flat: "文字", folded: "文字", opcodes: "equal:0:1:0:1 replace:1:2:1:2", changes: "原 文字\n改 文）" },
    Case { before: "b简到。到 。 到 ） 简（简从 \n, （从简a。,, 到 从从简 到a。\nb到\n（）,繁（b繁a（从b（\n简\nb从从b（到\nb\n,到ba。,,  从a\n到。。从）b,\n（从从繁b从繁a从,b到a,从简a从,。a繁。。\n从。b\n到从,,a\nb\na 从aa繁）ba 繁a,）baba\n简。）b（简 繁,繁b\n从简,,（b\n（b 从,aa,） （（\n从）（,繁。从\n）,（到） 繁繁简从从）（从\n,到。aa ba,（,））简。到）繁到到简简从）。,\n）（）到到a简\n,a,\n。。到从到 到简）a。简bb简\nab\naa到。从a", after: "b简到。到 。 到 ） 简（简从 \n, （从简a。,, 到 从从简 到a。\nb到\n（）,繁（b繁a（从b（\n简\nb从从b（到\nb\n,到ba。,,  从a\n到。。从）b,\n（从从繁b从繁a从,b到a,从简a从,。a繁。。\n从。b\n到从,,a\nb\na 从aa繁）ba 繁a,）baba\n简。）b（简 繁,繁b\n从简,,（b\n（b 从,aa,） （（\n从）（,繁。从\n）,（到） 繁繁简从从）（从\n,到。aa ba,（,））简。到）繁到到简简从）。,\n）（）到到a简\n,a,\n。。到从到 到简）a。简bb简\naa到。从a", prose_length: 217, trailing: 0, flat: "b简到。到 。 到 ） 简（简从 , （从简a。,, 到 从从简 到a。 b到 （）,繁（b繁a（从b（ 简 b从从b（到 b ,到ba。,, 从a 到。。从）b, （从从繁b从繁a从,b到a,从简a从,。a繁。。 从。b 到从,,a b a 从aa繁）ba 繁a,）baba 简。）b（简 繁,繁b 从简,,（b （b 从,aa,） （（ 从）（,繁。从 ）,（到） 繁繁简从从）（从 ,到。aa ba,（,））简。到）繁到到简简从）。, ）（）到到a简 ,a, 。。到从到 到简）a。简bb简 ab aa到。从a", folded: "b简到.到.到)简(简从,(从简a.,,到从从简到a.b到(),繁(b繁a(从b(简b从从b(到b,到ba.,,从a到..从)b,(从从繁b从繁a从,b到a,从简a从,.a繁..从.b到从,,aba从aa繁)ba繁a,)baba简.)b(简繁,繁b从简,,(b(b从,aa,)((从)(,繁.从),(到)繁繁简从从)(从,到.aaba,(,))简.到)繁到到简简从).,)()到到a简,a,..到从到到简)a.简bb简abaa到.从a", opcodes: "equal:0:252:0:252 replace:252:260:252:257", changes: "原 …简）a。简bb简 ab aa到。从a\n改 …简）a。简bb简 aa到。从a" },
    Case { before: "这一段是the文字文字the\n。the。这一段很短\nthe很短，\n这一段 是很短很短是，合成的\nthethe文字\n文字value 合成的。很短，\n。 value很短很短 \n文字很短很短文字很短the \nthethe这一段 ，这一段很短文字 。\n很短文字", after: "这一段是the字文字the\n。the。这一段很短\nthe很短，\n这一段 是很短很短是，合。 简简简繁the文字\n文字value 合成的。很短，\n简 valua。a。 a）文字很短很短文字很短the \nthethe这一段 ，这一段很短文字 。\n很短文字", prose_length: 110, trailing: 0, flat: "这一段是the文字文字the 。the。这一段很短 the很短， 这一段 是很短很短是，合成的 thethe文字 文字value 合成的。很短， 。 value很短很短 文字很短很短文字很短the thethe这一段 ，这一段很短文字 。 很短文字", folded: "这一段是the文字文字the.the.这一段很短the很短,这一段是很短很短是,合成的thethe文字文字value合成的.很短,.value很短很短文字很短很短文字很短thethethe这一段,这一段很短文字.很短文字", opcodes: "equal:0:7:0:7 delete:7:8:7:7 equal:8:45:7:44 replace:45:51:44:50 equal:51:73:50:72 replace:73:74:72:73 equal:74:79:73:78 replace:79:84:78:82 equal:84:85:82:83 replace:85:86:83:85 equal:86:126:85:125", changes: "原 这一段是the文字文字the 。th…\n改 这一段是the字文字the 。th…\n\n原 …段 是很短很短是，合成的 thethe文字 文字va…\n改 …段 是很短很短是，合。 简简简繁the文字 文字va…\n\n原 …e 合成的。很短， 。 value很短很短 文字很短很短文字很短…\n改 …e 合成的。很短， 简 valua。a。 a）文字很短很短文字很短…" },
    Case { before: "很短\n是。。是这一段。 很短很短合成的\n。 是是合成的the文字value文字是，。\n文字valuethe文字  很短是，。很短\n文字是", after: "繁b 从从很短\n是。。是这一段。 很短很短合成的\n。 是是合成的th,,e 字valu繁）,）到 简a字valuethe文字  很短是，。很短\n文字是", prose_length: 60, trailing: 0, flat: "很短 是。。是这一段。 很短很短合成的 。 是是合成的the文字value文字是，。 文字valuethe文字 很短是，。很短 文字是", folded: "很短是..是这一段.很短很短合成的.是是合成的the文字value文字是,.文字valuethe文字很短是,.很短文字是", opcodes: "insert:0:0:0:5 equal:0:29:5:34 insert:29:29:34:36 equal:29:30:36:37 replace:30:31:37:38 equal:31:36:38:43 replace:36:44:43:51 equal:44:68:51:75", changes: "原 很短 是。。是这一段…\n改 繁b 从从很短 是。。是这一段…\n\n原 … 。 是是合成的the文字value文字是，。 文字valuethe文…\n改 … 。 是是合成的th,,e 字valu繁）,）到 简a字valuethe文…" },
    Case { before: "b。", after: "b。", prose_length: 2, trailing: 0, flat: "b。", folded: "b.", opcodes: "equal:0:2:0:2", changes: "" },
    Case { before: "b\n己）（丙己丁丁）丙己戊）（从,戊己丙戊\n。戊\n丁。。丁丁（ 。到丙丙戊戊   到戊丙简丁\na从从 。b。到简,（\n丁丁）a繁繁）从戊从从戊 己\n丁丙简 戊从己,\n\nbb （,丁）丁a丁（\n简到简丁,到）\n）丙丁从b繁到丙简。丁a从）丁）己。简到己丁戊b到。）到丁繁丁丙bbb丙到简从,繁a简己）丙（到。繁繁戊简简丁）\n。, 丙）简a繁简从丁 到,到丙,丁戊到丙戊从己\n戊戊戊b\n（丙\n。己 戊戊", after: "b\n己）（丙己丁丁）丙己戊）（从,戊己丙戊\n。戊\n丁。。丁丁（ 。到丙丙戊戊   到戊丙简丁\na从从 。b。到简,（\n丁丁）a繁繁）从戊从从戊 己\n丁丙简 戊从己,\n\nbb （繁丁戊b（\n繁\n简到简丁,到）\n）丙丁从b繁到丙简。丁a从）丁）己。简到己丁戊b到。）到丁繁丁丙bbb丙到简从,繁a简己）丙（到。繁繁戊丙）简a繁简从丁 到,到丙,丁戊到丙戊从己\n戊戊戊b\n（丙\n。己 戊戊", prose_length: 174, trailing: 0, flat: "b 己）（丙己丁丁）丙己戊）（从,戊己丙戊 。戊 丁。。丁丁（ 。到丙丙戊戊 到戊丙简丁 a从从 。b。到简,（ 丁丁）a繁繁）从戊从从戊 己 丁丙简 戊从己, bb （,丁）丁a丁（ 简到简丁,到） ）丙丁从b繁到丙简。丁a从）丁）己。简到己丁戊b到。）到丁繁丁丙bbb丙到简从,繁a简己）丙（到。繁繁戊简简丁） 。, 丙）简a繁简从丁 到,到丙,丁戊到丙戊从己 戊戊戊b （丙 。己 戊戊", folded: "b己)(丙己丁丁)丙己戊)(从,戊己丙戊.戊丁..丁丁(.到丙丙戊戊到戊丙简丁a从从.b.到简,(丁丁)a繁繁)从戊从从戊己丁丙简戊从己,bb(,丁)丁a丁(简到简丁,到))丙丁从b繁到丙简.丁a从)丁)己.简到己丁戊b到.)到丁繁丁丙bbb丙到简从,繁a简己)丙(到.繁繁戊简简丁).,丙)简a繁简从丁到,到丙,丁戊到丙戊从己戊戊戊b(丙.己戊戊", opcodes: "equal:0:88:0:88 replace:88:89:88:89 equal:89:90:89:90 replace:90:94:90:92 equal:94:95:92:93 insert:95:95:93:95 equal:95:156:95:156 delete:156:164:156:156 equal:164:199:156:191", changes: "原 …戊从己, bb （,丁）丁a丁（ 简到简丁,到） ）…\n改 …戊从己, bb （繁丁戊b（ 繁 简到简丁,到） ）…\n\n原 …简己）丙（到。繁繁戊简简丁） 。, 丙）简a繁简从丁 到…\n改 …简己）丙（到。繁繁戊丙）简a繁简从丁 到…" },
    Case { before: "", after: "己繁b繁", prose_length: 0, trailing: 0, flat: "", folded: "", opcodes: "insert:0:0:0:4", changes: "原 \n改 己繁b繁" },
    Case { before: "a从到\n a）\n简） a繁从）。到。。到b（简aaa ba。简到b简\n,从  到。\n,从a,（）））从从,,到简 ） 简。（到a,ba（到。\n,\n,,a（从（（）到到。（）到）（简简 b简）a简繁到\n,到简（,到 bb到繁。 到繁,到bbbb简繁（）繁））到bb 简从繁（从。到。从 ,）繁b繁a\nba到。从从））到从\n简bb,ab繁,a繁繁）到）a, \nbb b, 到从从从）\n\n。简到b 到。繁到", after: "a从到\n a）\n简） a繁从）。到。。到b（简aaa ba,从  到。\n,从a,（）））从从,,到简 ） 简。（到a,ba（到。\n,\n,,a（从（（）到到。（）到）（简简 b（）a简繁到\n,到简（,到 bb到繁。 到繁,到bbbb简繁（）繁））到bb 简从繁（从。到。从 ,）繁b繁a\nba到。从从））b,ab繁,a繁繁）到）a, \nbb b, 到从从从）\n\n。简到b 到。繁到", prose_length: 172, trailing: 0, flat: "a从到 a） 简） a繁从）。到。。到b（简aaa ba。简到b简 ,从 到。 ,从a,（）））从从,,到简 ） 简。（到a,ba（到。 , ,,a（从（（）到到。（）到）（简简 b简）a简繁到 ,到简（,到 bb到繁。 到繁,到bbbb简繁（）繁））到bb 简从繁（从。到。从 ,）繁b繁a ba到。从从））到从 简bb,ab繁,a繁繁）到）a, bb b, 到从从从） 。简到b 到。繁到", folded: "a从到a)简)a繁从).到..到b(简aaaba.简到b简,从到.,从a,()))从从,,到简)简.(到a,ba(到.,,,a(从(()到到.()到)(简简b简)a简繁到,到简(,到bb到繁.到繁,到bbbb简繁()繁))到bb简从繁(从.到.从,)繁b繁aba到.从从))到从简bb,ab繁,a繁繁)到)a,bbb,到从从从).简到b到.繁到", opcodes: "equal:0:29:0:29 delete:29:35:29:29 equal:35:93:29:87 replace:93:94:87:88 equal:94:157:88:151 delete:157:162:151:151 equal:162:200:151:189", changes: "原 …到b（简aaa ba。简到b简 ,从 到。 ,从a…\n改 …到b（简aaa ba,从 到。 ,从a…\n\n原 …。（）到）（简简 b简）a简繁到 ,到简（…\n改 …。（）到）（简简 b（）a简繁到 ,到简（…\n\n原 …a ba到。从从））到从 简bb,ab繁,a繁繁）…\n改 …a ba到。从从））b,ab繁,a繁繁）…" },
    Case { before: "）到。从到简丙", after: "）到。从到简丙,。简到从丙", prose_length: 7, trailing: 0, flat: "）到。从到简丙", folded: ")到.从到简丙", opcodes: "equal:0:7:0:7 insert:7:7:7:13", changes: "原 ）到。从到简丙\n改 ）到。从到简丙,。简到从丙" },
    Case { before: "，", after: "）\n\n", prose_length: 1, trailing: 0, flat: "，", folded: ",", opcodes: "replace:0:1:0:3", changes: "原 ，\n改 ）" },
    Case { before: "，", after: "），", prose_length: 1, trailing: 0, flat: "，", folded: ",", opcodes: "insert:0:0:0:1 equal:0:1:1:2", changes: "原 ，\n改 ），" },
    Case { before: "这一段\n是合成的value文字 the，。。这一段是很短合成的。value\n the合成的合成的，合成的the 文字是 the这一段很短这一段文字the是value。是合成的文字\nthe。 value\n。the合成的value是这一段是是合成的\n 很短\n  这一段很短合成的这一段\n合成的合成的，合成的是value。value\n 很短文字 这一段很短这一段文字是很短", after: "这一段\n是合成的value文字 the，。。这一段是很短合成的。value\n the合成的合成的，合成的the 文字是 the这一段很短这一段文字the是value。是合成的文字\nthe。 value\n。the合成的value是这一段是是合成的\n 很短\n  这一段很短合成的这一段\n合成的合成的，合成的是）b到ue。value\n 很短文字 这一段很短这一段文字是很短", prose_length: 165, trailing: 0, flat: "这一段 是合成的value文字 the，。。这一段是很短合成的。value the合成的合成的，合成的the 文字是 the这一段很短这一段文字the是value。是合成的文字 the。 value 。the合成的value是这一段是是合成的 很短 这一段很短合成的这一段 合成的合成的，合成的是value。value 很短文字 这一段很短这一段文字是很短", folded: "这一段是合成的value文字the,..这一段是很短合成的.valuethe合成的合成的,合成的the文字是the这一段很短这一段文字the是value.是合成的文字the.value.the合成的value是这一段是是合成的很短这一段很短合成的这一段合成的合成的,合成的是value.value很短文字这一段很短这一段文字是很短", opcodes: "equal:0:152:0:152 replace:152:155:152:155 equal:155:183:155:183", changes: "原 …成的合成的，合成的是value。value …\n改 …成的合成的，合成的是）b到ue。value …" },
    Case { before: "繁从到）繁到 ,b\n到到简。繁（。aab）（繁 ab））b\n繁 b\n）bb\n）\n简到\n从）。（a（到到,从b从\nb从）。 繁）a简 简。ab到（。,b从从 （）繁繁ab,（\n（,）繁繁从到 （（b（ba,,到（b到a到从到简（\n。ba从到b繁ab,到））（（。  ,简繁, 简简\nb）从 ,a 繁 ,,a,从繁简繁到\n到,b繁a简（简b从繁（,到）a简 到（。）简简,繁（到）到到 a从。从到到从到 ,,。a）繁繁）简a简从 。（ 简（\n简从bb繁从,a（babba,\n\n（ 到繁\n）（,（到简\n。简 ））从到繁。b从简", after: "繁从到）繁到 ,b\n到到简。繁（。aab）（繁 ab））b\n繁 b\n）bb\n）\n简到\n从）。（a（到到,从b从\nb从）。 繁）a简 简。ab到（。,b从从 （）繁繁ab,（\n（,）繁繁从到 （,到（b到a到从到简（\n。ba从到b繁ab,到））（（。  ,简繁, 简简\nb）从 ,a 繁 ,,a,从繁简繁到\n到,b繁a简（简b从繁（,到）a简 到（。）简简,繁（到）到到 a从。从到,\n到。,,。a）繁繁）简a到。 。（ 简（\n简从bb繁从,a（babba,\n\n（ 到繁\n）到）（,简\n。简 ））从到繁。b从简", prose_length: 224, trailing: 0, flat: "繁从到）繁到 ,b 到到简。繁（。aab）（繁 ab））b 繁 b ）bb ） 简到 从）。（a（到到,从b从 b从）。 繁）a简 简。ab到（。,b从从 （）繁繁ab,（ （,）繁繁从到 （（b（ba,,到（b到a到从到简（ 。ba从到b繁ab,到））（（。 ,简繁, 简简 b）从 ,a 繁 ,,a,从繁简繁到 到,b繁a简（简b从繁（,到）a简 到（。）简简,繁（到）到到 a从。从到到从到 ,,。a）繁繁）简a简从 。（ 简（ 简从bb繁从,a（babba, （ 到繁 ）（,（到简 。简 ））从到繁。b从简", folded: "繁从到)繁到,b到到简.繁(.aab)(繁ab))b繁b)bb)简到从).(a(到到,从b从b从).繁)a简简.ab到(.,b从从()繁繁ab,((,)繁繁从到((b(ba,,到(b到a到从到简(.ba从到b繁ab,到))((.,简繁,简简b)从,a繁,,a,从繁简繁到到,b繁a简(简b从繁(,到)a简到(.)简简,繁(到)到到a从.从到到从到,,.a)繁繁)简a简从.(简(简从bb繁从,a(babba,(到繁)(,(到简.简))从到繁.b从简", opcodes: "equal:0:96:0:96 replace:96:260:96:254", changes: "原 … （,）繁繁从到 （（b（ba,,到（b到a到从到简（ 。ba从到b繁ab,到））（（。 ,简繁, 简简 b）从 ,a 繁 ,,a,从繁简繁到 到,b繁a简（简b从繁（,到）a简 到（。）简简,繁（到）到到 a从。从到到从到 ,,。a）繁繁）简a简从 。（ 简（ 简从bb繁从,a（babba, （ 到繁 ）（,（到简 。简 ））从到繁。b从简\n改 … （,）繁繁从到 （,到（b到a到从到简（ 。ba从到b繁ab,到））（（。 ,简繁, 简简 b）从 ,a 繁 ,,a,从繁简繁到 到,b繁a简（简b从繁（,到）a简 到（。）简简,繁（到）到到 a从。从到, 到。,,。a）繁繁）简a到。 。（ 简（ 简从bb繁从,a（babba, （ 到繁 ）到）（,简 。简 ））从到繁。b从简" },
    Case { before: "a\n到从。a。。。繁。）,。。 繁从繁）。到a到从 从a\nbb到。）（到a,简 \n）\n繁简a\n从\n到,（\n到。a（简a从简aa简a从。从ba繁aba（。, 简,繁）繁）到从从到。从（到（\n\n到到从b（,,,。到\n从ba）b到 到简\n繁,繁繁从\n繁\na\n ） 繁,繁。到从 繁,,（到。\n到繁从从\n（简a,繁a\n 。繁（b到到,,,到 ,。（ba到 ba从bb。\n,） （繁 。,繁繁b到）,）b到b", after: "a\n到从。a。。,）。繁。）,。。 繁从繁）。到a到从 从a\nbb到。）（到a,简 \n）\n繁简a\n从\n到,（\n到。a（简a从简aa简a从。从ba繁aba（。, 简,繁）繁）到从从到。从（到（\n\n到到从b（,,,。到\n从ba）b到 到简\n繁,繁繁从\n繁\na\n ） 繁,繁。\nbb 从从b到。\n到繁从从\n（简a,繁a\n 。繁（b到到,,b。繁（简（ba到 ba从bb。\n,） （繁 。,繁繁b到）,）b到繁（。bb", prose_length: 168, trailing: 0, flat: "a 到从。a。。。繁。）,。。 繁从繁）。到a到从 从a bb到。）（到a,简 ） 繁简a 从 到,（ 到。a（简a从简aa简a从。从ba繁aba（。, 简,繁）繁）到从从到。从（到（ 到到从b（,,,。到 从ba）b到 到简 繁,繁繁从 繁 a ） 繁,繁。到从 繁,,（到。 到繁从从 （简a,繁a 。繁（b到到,,,到 ,。（ba到 ba从bb。 ,） （繁 。,繁繁b到）,）b到b", folded: "a到从.a...繁.),..繁从繁).到a到从从abb到.)(到a,简)繁简a从到,(到.a(简a从简aa简a从.从ba繁aba(.,简,繁)繁)到从从到.从(到(到到从b(,,,.到从ba)b到到简繁,繁繁从繁a)繁,繁.到从繁,,(到.到繁从从(简a,繁a.繁(b到到,,,到,.(ba到ba从bb.,)(繁.,繁繁b到),)b到b", opcodes: "equal:0:8:0:8 replace:8:199:8:205", changes: "原 a 到从。a。。。繁。）,。。 繁从繁）。到a到从 从a bb到。）（到a,简 ） 繁简a 从 到,（ 到。a（简a从简aa简a从。从ba繁aba（。, 简,繁）繁）到从从到。从（到（ 到到从b（,,,。到 从ba）b到 到简 繁,繁繁从 繁 a ） 繁,繁。到从 繁,,（到。 到繁从从 （简a,繁a 。繁（b到到,,,到 ,。（ba到 ba从bb。 ,） （繁 。,繁繁b到）,）b到b\n改 a 到从。a。。,）。繁。）,。。 繁从繁）。到a到从 从a bb到。）（到a,简 ） 繁简a 从 到,（ 到。a（简a从简aa简a从。从ba繁aba（。, 简,繁）繁）到从从到。从（到（ 到到从b（,,,。到 从ba）b到 到简 繁,繁繁从 繁 a ） 繁,繁。 bb 从从b到。 到繁从从 （简a,繁a 。繁（b到到,,b。繁（简（ba到 ba从bb。 ,） （繁 。,繁繁b到）,）b到繁（。bb" },
    Case { before: "。the是\n文字 the是这一段合成的这一段value是这一段the很短the很短是是很短  是文字， 这一段，文字很短这一段合成的，\n 。是合成的。", after: "。the是\n文字 the是这一段合成的这一段value是这一段the很短the很短是是很短  是文字， 这一段，文字很短这一段合成的，。是合成的。", prose_length: 68, trailing: 0, flat: "。the是 文字 the是这一段合成的这一段value是这一段the很短the很短是是很短 是文字， 这一段，文字很短这一段合成的， 。是合成的。", folded: ".the是文字the是这一段合成的这一段value是这一段the很短the很短是是很短是文字,这一段,文字很短这一段合成的,.是合成的.", opcodes: "equal:0:67:0:67 delete:67:69:67:67 equal:69:75:67:73", changes: "" },
    Case { before: "\n。繁繁繁ba\n简从\n到 简（到。（到）繁到\n简a\n（, （\n,b简。b）从a（  bb ） （aa（从 从\n简。）。简繁繁\n） ,。。\n）（a））\n简繁简简到到 从\n到。从到（\n（到,b\n从（a到a,a简。到繁 。\n从（从a简ba,）a从从a,）b。）\n简\n（a简\n简。）（繁从a到（a,\n繁。从 到 （到\n从简bb。到,。。。\n到繁到简）繁）到,a从繁 ）。从b （a。。,,（ a到从  （  从b ,到 繁 从ab。简,b\n繁繁（简\na从（（\n到）\n）bb,）,。,（（繁简a）a\n）简（\n。a（b从\n繁。a（从", after: "\n。繁繁繁ba\n简从\n到 简（到。（到）繁到\n简a\n（, （\n,b简。b）从a（  bb ） （aa（从 从\n简。）。简繁繁\n） ,。。\n）（a））\n简繁简简到到 从\n到。从到（\n（到,b\n从（a到a,a简。到繁 。\n从（从a简ba,）a从从a,）b。）\n简\n（a简\n简。）（繁从a到（a,\n繁。从 到 （到\n从简bb。到,。。。\n到繁到简）繁）到,a从繁 ）。从b （a。。,,（ a到从  （  从b ,到 繁 从ab。简,b\n繁繁（简\na从（（\n到）\n）bb,）,。,（（繁简a）a\n）简（\n。a（b从\n繁。a（从", prose_length: 211, trailing: 0, flat: "。繁繁繁ba 简从 到 简（到。（到）繁到 简a （, （ ,b简。b）从a（ bb ） （aa（从 从 简。）。简繁繁 ） ,。。 ）（a）） 简繁简简到到 从 到。从到（ （到,b 从（a到a,a简。到繁 。 从（从a简ba,）a从从a,）b。） 简 （a简 简。）（繁从a到（a, 繁。从 到 （到 从简bb。到,。。。 到繁到简）繁）到,a从繁 ）。从b （a。。,,（ a到从 （ 从b ,到 繁 从ab。简,b 繁繁（简 a从（（ 到） ）bb,）,。,（（繁简a）a ）简（ 。a（b从 繁。a（从", folded: ".繁繁繁ba简从到简(到.(到)繁到简a(,(,b简.b)从a(bb)(aa(从从简.).简繁繁),..)(a))简繁简简到到从到.从到((到,b从(a到a,a简.到繁.从(从a简ba,)a从从a,)b.)简(a简简.)(繁从a到(a,繁.从到(到从简bb.到,...到繁到简)繁)到,a从繁).从b(a..,,(a到从(从b,到繁从ab.简,b繁繁(简a从((到))bb,),.,((繁简a)a)简(.a(b从繁.a(从", opcodes: "equal:0:260:0:260", changes: "" },
    Case { before: "。a 。繁a简", after: "。a 。繁a（简）简", prose_length: 6, trailing: 0, flat: "。a 。繁a简", folded: ".a.繁a简", opcodes: "equal:0:6:0:6 insert:6:6:6:7 equal:6:7:7:8 insert:7:7:8:10", changes: "原 。a 。繁a简\n改 。a 。繁a（简）简" },
    Case { before: "从简）戊从（丙（bb丁 戊丁戊。\n从丁丁繁a从丙\n戊a戊,丁）己a）到（b。aa。,戊简从从到b丁。己到\n繁 \na戊\n（戊b戊b繁到\na从）（）b 简己丁ab,丁简 从繁b）简）戊简丙）简丁丙到）己）从丙简简（简b简a（ 戊简\nb a,从。", after: "从简）戊从（丙（bb丁 戊丁到\n\n从丁丁繁a从丙\n戊a戊,丁）己a）到（b。aa。,戊简从从到b丁。己到\n繁 \na戊\n（戊b戊b繁到\na从）（）b 简己丁ab,丁简 从繁b）简简b从（）戊简丙）简丁丙到）己）从丙简简（简b简a（ 戊简\nb a,从。", prose_length: 107, trailing: 0, flat: "从简）戊从（丙（bb丁 戊丁戊。 从丁丁繁a从丙 戊a戊,丁）己a）到（b。aa。,戊简从从到b丁。己到 繁 a戊 （戊b戊b繁到 a从）（）b 简己丁ab,丁简 从繁b）简）戊简丙）简丁丙到）己）从丙简简（简b简a（ 戊简 b a,从。", folded: "从简)戊从(丙(bb丁戊丁戊.从丁丁繁a从丙戊a戊,丁)己a)到(b.aa.,戊简从从到b丁.己到繁a戊(戊b戊b繁到a从)()b简己丁ab,丁简从繁b)简)戊简丙)简丁丙到)己)从丙简简(简b简a(戊简ba,从.", opcodes: "equal:0:14:0:14 replace:14:16:14:16 equal:16:88:16:88 insert:88:88:88:92 equal:88:120:92:124", changes: "原 …从（丙（bb丁 戊丁戊。 从丁丁繁a从丙 戊…\n改 …从（丙（bb丁 戊丁到 从丁丁繁a从丙 戊…\n\n原 …b,丁简 从繁b）简）戊简丙）简丁丙到）…\n改 …b,丁简 从繁b）简简b从（）戊简丙）简丁丙到）…" },
    Case { before: "繁简（到到a繁。。繁繁。繁a到简 ）。 简简）简a\n（,简b,b从\na\n）从b繁繁。）简（\n a简（b从）aa到）从）（到 从简。简b（））到\n 简（（（ ）a。从从 ba,\na\n从繁简a）从）简  ））a\n到 （,繁b）。 b。简从。（bb aa）繁到）。繁从, a）（简 a。,a\n a,到到。a（到到,,b到从。b。\n（（（简ab,a 。简从从（简。ab\na到繁从到（到简）bb 繁到到ba,）\n", after: "繁简（到到a繁。。繁繁。繁a到简 ）。 简简）简a\n（,简b,b从\na\n）从b繁繁。）简（\n a简（b从）aa到）从）（到 从简。简b（））到\n 简（（（ ）a。从从 ba,\na\n从繁简a）从）简  ））a\n到 （,繁b）。 b。简从。（bb aa）繁到）。繁从, a）（简 a。,a\n a,到到。a（到到,,b到从。b。\n（（（简ab,a 。简从从（简。ab\na到繁从到（到简）bb 繁到到ba,）\n", prose_length: 172, trailing: 1, flat: "繁简（到到a繁。。繁繁。繁a到简 ）。 简简）简a （,简b,b从 a ）从b繁繁。）简（ a简（b从）aa到）从）（到 从简。简b（））到 简（（（ ）a。从从 ba, a 从繁简a）从）简 ））a 到 （,繁b）。 b。简从。（bb aa）繁到）。繁从, a）（简 a。,a a,到到。a（到到,,b到从。b。 （（（简ab,a 。简从从（简。ab a到繁从到（到简）bb 繁到到ba,）", folded: "繁简(到到a繁..繁繁.繁a到简).简简)简a(,简b,b从a)从b繁繁.)简(a简(b从)aa到)从)(到从简.简b())到简((()a.从从ba,a从繁简a)从)简))a到(,繁b).b.简从.(bbaa)繁到).繁从,a)(简a.,aa,到到.a(到到,,b到从.b.(((简ab,a.简从从(简.aba到繁从到(到简)bb繁到到ba,)", opcodes: "equal:0:201:0:201", changes: "" },
    Case { before: "从a,繁,bb简,简（（繁简。简\n）b。 到（ 到 \n（简,到从（ （简。a。从） ）从）b简,简简,）\n从 b到繁繁到 a\n\nb（简\n\n简 。繁繁繁aaa）繁（\n ）。））\nb（到,a。繁到。从b繁简\n简\n到到）a从繁）,繁。\n繁到）,,从 a） b从 。\n从繁\nb简）。繁。b简b从 简\n）b繁（。繁\n。 ,b（ba（从简繁\na从简到到（简到  从b\nb从。,简 简繁繁简到a从从a,\n从）。a到）  到简abb繁到a,\na）。\n。\n从 从。,a（ab从,简从繁\n繁a\n从。（。。。）从（到b\n 繁从繁繁,简从 ）到", after: "从a,繁,bb简,简（（繁简。。 到（ 到 \n（简,到从（ （简。a。从） ）从）b简,简简,）\n从 b到繁繁到 a\n\nb（简\n\n简 。繁繁繁aaa）繁（\n ）。））\nb（到,a。繁到。从b繁简\n简\n到到）a从繁）,繁。\n繁到）,,从 a） b从 。\n从繁\nb简）。繁。b简b从 简\n）b繁（。繁\n。 ,b（ba（从简繁\na从简到到（简到  从b\nb从。,简 简繁繁简到a从从a,\n从）。a到）  到简abb繁到a。\n从 从。,a（ab从,简从繁\n繁a\n从。（。。。）从（到b\n 繁从繁繁,简从 ）到", prose_length: 213, trailing: 0, flat: "从a,繁,bb简,简（（繁简。简 ）b。 到（ 到 （简,到从（ （简。a。从） ）从）b简,简简,） 从 b到繁繁到 a b（简 简 。繁繁繁aaa）繁（ ）。）） b（到,a。繁到。从b繁简 简 到到）a从繁）,繁。 繁到）,,从 a） b从 。 从繁 b简）。繁。b简b从 简 ）b繁（。繁 。 ,b（ba（从简繁 a从简到到（简到 从b b从。,简 简繁繁简到a从从a, 从）。a到） 到简abb繁到a, a）。 。 从 从。,a（ab从,简从繁 繁a 从。（。。。）从（到b 繁从繁繁,简从 ）到", folded: "从a,繁,bb简,简((繁简.简)b.到(到(简,到从((简.a.从))从)b简,简简,)从b到繁繁到ab(简简.繁繁繁aaa)繁().))b(到,a.繁到.从b繁简简到到)a从繁),繁.繁到),,从a)b从.从繁b简).繁.b简b从简)b繁(.繁.,b(ba(从简繁a从简到到(简到从bb从.,简简繁繁简到a从从a,从).a到)到简abb繁到a,a)..从从.,a(ab从,简从繁繁a从.(...)从(到b繁从繁繁,简从)到", opcodes: "equal:0:15:0:15 replace:15:260:15:250", changes: "原 …bb简,简（（繁简。简 ）b。 到（ 到 （简,到从（ （简。a。从） ）从）b简,简简,） 从 b到繁繁到 a b（简 简 。繁繁繁aaa）繁（ ）。）） b（到,a。繁到。从b繁简 简 到到）a从繁）,繁。 繁到）,,从 a） b从 。 从繁 b简）。繁。b简b从 简 ）b繁（。繁 。 ,b（ba（从简繁 a从简到到（简到 从b b从。,简 简繁繁简到a从从a, 从）。a到） 到简abb繁到a, a）。 。 从 从。,a（ab从,简从繁 繁a 从。（。。。）从（到b 繁从繁繁,简从 ）到\n改 …bb简,简（（繁简。。 到（ 到 （简,到从（ （简。a。从） ）从）b简,简简,） 从 b到繁繁到 a b（简 简 。繁繁繁aaa）繁（ ）。）） b（到,a。繁到。从b繁简 简 到到）a从繁）,繁。 繁到）,,从 a） b从 。 从繁 b简）。繁。b简b从 简 ）b繁（。繁 。 ,b（ba（从简繁 a从简到到（简到 从b b从。,简 简繁繁简到a从从a, 从）。a到） 到简abb繁到a。 从 从。,a（ab从,简从繁 繁a 从。（。。。）从（到b 繁从繁繁,简从 ）到" },
    Case { before: "。简从到（b\n从,到\n（b（\na从。b（\n 。 。\n\n到ab简,\n（到a到a）\n从从b繁从a（繁简简到简）繁到 ）从,从从到）简（）aa\n繁（繁繁繁从繁到a,简到） ,繁繁简）简 b到\n从）,a繁a\n繁  a繁）,。）\na。从,简a从b繁 。繁b从从到繁,b\n,ba  a\n繁从到从从b（b到）aa。 ,a简a\n,b简,,繁）aa\nb繁（从（繁繁）从从（b,简。,b\n\n到,从繁\n繁,,b （（）\n\na。\n\n（\na 到\n", after: "。简从到（b）\n从,到\n（b（\na从。b（\n 。 。\n\n到ab简,\n（到a到a）\n从从b繁从a（繁简简到简）繁到 ）从,从从到）简（）aa\n繁（繁繁繁从繁到a,简到） ,繁繁简）简 b到\n从）,a繁a\n繁  a繁）,。）\na。从,）a\n）从简a从bb\n,a。ab到繁,b\n,ba  a\n繁从到从从b（b到）aa。 ,a简a\n,b简,,繁）aa\nb繁（从（繁繁）从从（b,简。,b\n\n到,从繁\n繁,,b （（）\n\na。\n\n（\na 到\n", prose_length: 172, trailing: 1, flat: "。简从到（b 从,到 （b（ a从。b（ 。 。 到ab简, （到a到a） 从从b繁从a（繁简简到简）繁到 ）从,从从到）简（）aa 繁（繁繁繁从繁到a,简到） ,繁繁简）简 b到 从）,a繁a 繁 a繁）,。） a。从,简a从b繁 。繁b从从到繁,b ,ba a 繁从到从从b（b到）aa。 ,a简a ,b简,,繁）aa b繁（从（繁繁）从从（b,简。,b 到,从繁 繁,,b （（） a。 （ a 到", folded: ".简从到(b从,到(b(a从.b(..到ab简,(到a到a)从从b繁从a(繁简简到简)繁到)从,从从到)简()aa繁(繁繁繁从繁到a,简到),繁繁简)简b到从),a繁a繁a繁),.)a.从,简a从b繁.繁b从从到繁,b,baa繁从到从从b(b到)aa.,a简a,b简,,繁)aab繁(从(繁繁)从从(b,简.,b到,从繁繁,,b(()a.(a到", opcodes: "equal:0:6:0:6 replace:6:210:6:216", changes: "原 。简从到（b 从,到 （b（ a从。b（ 。 。 到ab简, （到a到a） 从从b繁从a（繁简简到简）繁到 ）从,从从到）简（）aa 繁（繁繁繁从繁到a,简到） ,繁繁简）简 b到 从）,a繁a 繁 a繁）,。） a。从,简a从b繁 。繁b从从到繁,b ,ba a 繁从到从从b（b到）aa。 ,a简a ,b简,,繁）aa b繁（从（繁繁）从从（b,简。,b 到,从繁 繁,,b （（） a。 （ a 到\n改 。简从到（b） 从,到 （b（ a从。b（ 。 。 到ab简, （到a到a） 从从b繁从a（繁简简到简）繁到 ）从,从从到）简（）aa 繁（繁繁繁从繁到a,简到） ,繁繁简）简 b到 从）,a繁a 繁 a繁）,。） a。从,）a ）从简a从bb ,a。ab到繁,b ,ba a 繁从到从从b（b到）aa。 ,a简a ,b简,,繁）aa b繁（从（繁繁）从从（b,简。,b 到,从繁 繁,,b （（） a。 （ a 到" },
    Case { before: ",从b到简简a（b）,）,a）繁。。,\n,a。 ）） , b（（到简） 。a到a", after: ",从b到简简（ 从（到a）繁。。,\n,a。 ）） 。\n\n从（到简） 。a到a", prose_length: 35, trailing: 0, flat: ",从b到简简a（b）,）,a）繁。。, ,a。 ）） , b（（到简） 。a到a", folded: ",从b到简简a(b),),a)繁..,,a.)),b((到简).a到a", opcodes: "equal:0:6:0:6 delete:6:7:6:6 equal:7:8:6:7 replace:8:13:7:11 equal:13:27:11:25 replace:27:31:25:29 equal:31:40:29:38", changes: "原 ,从b到简简a（b）,）,a）繁。。, ,a。…\n改 ,从b到简简（ 从（到a）繁。。, ,a。…\n\n原 …。, ,a。 ）） , b（（到简） 。a到a\n改 …。, ,a。 ）） 。 从（到简） 。a到a" },
    Case { before: "这一段", after: "段", prose_length: 3, trailing: 0, flat: "这一段", folded: "这一段", opcodes: "delete:0:2:0:0 equal:2:3:0:1", changes: "原 这一段\n改 段" },
    Case { before: "从（（ 到简））,）a到到a）（aab简繁从（,（\n,简a从简b到 简从到（（a到a到从（）简ba简简\n简繁简,。b。从b（到到\n）,从（到到a\n 简简繁（\n）,。）。\n,从\n）b（\n 简a\n\n从a,（。 到 。\n（从\n简a（, ,到ba简从\n。从, ）（到,。\n繁（繁b简, 简从a,a 到）b简从从简,b繁。（。\n,从b\n（\n简繁ab简）a）（到。繁简。（ 繁（。从。。简 繁a简（繁繁 ）a", after: "a,\n从（（ 到简））,）a到到a）（aab简繁从（,（\n,简a从简b到 简从到（（a到a到从（）简ba简简\n简繁简,。b。从b（到到\n）,从（到到a\n 简简繁（\n）,。）。\n,从\n）b（\n 简a\n\n从a,（。 到 。\n（从\n简a（, ,到ba简从\n。从, ）（到,。\n繁（繁b简, 简从a,（,,a 到）b简从从简,b繁。（。\n,从b\n（\n简繁ab简）a）（到。繁简。（ 繁（。从。。简 繁a简（繁繁 ）a", prose_length: 168, trailing: 0, flat: "从（（ 到简））,）a到到a）（aab简繁从（,（ ,简a从简b到 简从到（（a到a到从（）简ba简简 简繁简,。b。从b（到到 ）,从（到到a 简简繁（ ）,。）。 ,从 ）b（ 简a 从a,（。 到 。 （从 简a（, ,到ba简从 。从, ）（到,。 繁（繁b简, 简从a,a 到）b简从从简,b繁。（。 ,从b （ 简繁ab简）a）（到。繁简。（ 繁（。从。。简 繁a简（繁繁 ）a", folded: "从((到简)),)a到到a)(aab简繁从(,(,简a从简b到简从到((a到a到从()简ba简简简繁简,.b.从b(到到),从(到到a简简繁(),.).,从)b(简a从a,(.到.(从简a(,,到ba简从.从,)(到,.繁(繁b简,简从a,a到)b简从从简,b繁.(.,从b(简繁ab简)a)(到.繁简.(繁(.从..简繁a简(繁繁)a", opcodes: "replace:0:198:0:204", changes: "原 从（（ 到简））,）a到到a）（aab简繁从（,（ ,简a从简b到 简从到（（a到a到从（）简ba简简 简繁简,。b。从b（到到 ）,从（到到a 简简繁（ ）,。）。 ,从 ）b（ 简a 从a,（。 到 。 （从 简a（, ,到ba简从 。从, ）（到,。 繁（繁b简, 简从a,a 到）b简从从简,b繁。（。 ,从b （ 简繁ab简）a）（到。繁简。（ 繁（。从。。简 繁a简（繁繁 ）a\n改 a, 从（（ 到简））,）a到到a）（aab简繁从（,（ ,简a从简b到 简从到（（a到a到从（）简ba简简 简繁简,。b。从b（到到 ）,从（到到a 简简繁（ ）,。）。 ,从 ）b（ 简a 从a,（。 到 。 （从 简a（, ,到ba简从 。从, ）（到,。 繁（繁b简, 简从a,（,,a 到）b简从从简,b繁。（。 ,从b （ 简繁ab简）a）（到。繁简。（ 繁（。从。。简 繁a简（繁繁 ）a" },
    Case { before: "\n是thevalue 合成的文字 合成的\n合成的valuethe文字合成的合成的， 合成的\n。很短这一段这一段。这一段value文字 是\n\nvalue这一段 value文字。是，value是， ，value。。 这一段这一段这一段the合成的，。the是很短value\n。 \n 合成的是。，。 这一段文字很短。\n。合成的value 这一段the文字 the合成的", after: "\n是thevalu合成的\n合成的valuethe文字合成的合成的， 合成的\n。很短这一段这一段。这一段value文字 是\n\nvalue这一段 value文字。是，value是， ，value。。 这一段这一段这一段从the合成的，。t繁a,到简,alue是。，。 这一段文字很短。\n。合成的value 这一段the文字 the合成的", prose_length: 161, trailing: 0, flat: "是thevalue 合成的文字 合成的 合成的valuethe文字合成的合成的， 合成的 。很短这一段这一段。这一段value文字 是 value这一段 value文字。是，value是， ，value。。 这一段这一段这一段the合成的，。the是很短value 。 合成的是。，。 这一段文字很短。 。合成的value 这一段the文字 the合成的", folded: "是thevalue合成的文字合成的合成的valuethe文字合成的合成的,合成的.很短这一段这一段.这一段value文字是value这一段value文字.是,value是,,value..这一段这一段这一段the合成的,.the是很短value.合成的是.,.这一段文字很短..合成的value这一段the文字the合成的", opcodes: "equal:0:9:0:9 delete:9:17:9:9 equal:17:115:9:107 insert:115:115:107:108 equal:115:124:108:117 replace:124:130:117:123 equal:130:134:123:127 delete:134:142:127:127 equal:142:181:127:166", changes: "原 是thevalue 合成的文字 合成的 合成的val…\n改 是thevalu合成的 合成的val…\n\n原 … 这一段这一段这一段the合成的，。th…\n改 … 这一段这一段这一段从the合成的，。th…\n\n原 …段the合成的，。the是很短value 。 合成的是。，。 这一段文字…\n改 …段the合成的，。t繁a,到简,alue是。，。 这一段文字…" },
    Case { before: " 文字是这一段文字是the是\n，。很短 这一段。很短\n。\n很短是 这一段value \n这一段value\n。这一段，文字合成的value，\n是是，文字the很短。the这一段，。。，很短 合成的。value，，valuevalue很短很短，\n。这一段合成的 value，，", after: " 文字是这一段文字是the是\n，。很短 这一段。很短\n。\n很短是 这一段value \n这一段value\n。这一段，文字合成的value，\n是是，文字t到e很短。the这一段，。。，很短 合成的。value，，valuevalue很短很短，\n。这一段合成的 value，，", prose_length: 122, trailing: 0, flat: "文字是这一段文字是the是 ，。很短 这一段。很短 。 很短是 这一段value 这一段value 。这一段，文字合成的value， 是是，文字the很短。the这一段，。。，很短 合成的。value，，valuevalue很短很短， 。这一段合成的 value，，", folded: "文字是这一段文字是the是,.很短这一段.很短.很短是这一段value这一段value.这一段,文字合成的value,是是,文字the很短.the这一段,..,很短合成的.value,,valuevalue很短很短,.这一段合成的value,,", opcodes: "equal:0:75:0:75 replace:75:76:75:76 equal:76:135:76:135", changes: "原 …ue， 是是，文字the很短。the这一段…\n改 …ue， 是是，文字t到e很短。the这一段…" },
    Case { before: " ,\n\n从简））繁b。繁繁\n,\n简繁。（）a。b到繁a繁） 从）简）从简 ）到繁", after: " ,\n\n从简））繁\n,\n简繁。（）a。b到繁a繁） 从）简）从简 ）到繁", prose_length: 33, trailing: 0, flat: ", 从简））繁b。繁繁 , 简繁。（）a。b到繁a繁） 从）简）从简 ）到繁", folded: ",从简))繁b.繁繁,简繁.()a.b到繁a繁)从)简)从简)到繁", opcodes: "equal:0:8:0:8 delete:8:12:8:8 equal:12:40:8:36", changes: "原 , 从简））繁b。繁繁 , 简繁。（）a…\n改 , 从简））繁 , 简繁。（）a…" },
    Case { before: "，。。\n文字文字这一段是，，value value", after: "，。。\n文字文字这一ealue", prose_length: 23, trailing: 0, flat: "，。。 文字文字这一段是，，value value", folded: ",..文字文字这一段是,,valuevalue", opcodes: "equal:0:10:0:10 replace:10:15:10:11 equal:15:19:11:15 delete:19:25:15:15", changes: "原 ，。。 文字文字这一段是，，value value\n改 ，。。 文字文字这一ealue" },
    Case { before: "b", after: "简bb", prose_length: 1, trailing: 0, flat: "b", folded: "b", opcodes: "insert:0:0:0:1 equal:0:1:1:2 insert:1:1:2:3", changes: "原 b\n改 简bb" },
    Case { before: "（", after: "（（", prose_length: 1, trailing: 0, flat: "（", folded: "(", opcodes: "equal:0:1:0:1 insert:1:1:1:2", changes: "原 （\n改 （（" },
    Case { before: "）繁,,\n。 ,\n）到 到从（aa\n。,从到。,。）。,b,\n\n\n\nb）,繁,繁", after: "）繁,,\n）到 到从（aa\n。,从到。,。）。,b,\n\n\n\nb）,繁,繁", prose_length: 31, trailing: 0, flat: "）繁,, 。 , ）到 到从（aa 。,从到。,。）。,b, b）,繁,繁", folded: ")繁,,.,)到到从(aa.,从到.,.).,b,b),繁,繁", opcodes: "equal:0:3:0:3 delete:3:7:3:3 equal:7:40:3:36", changes: "原 ）繁,, 。 , ）到 到从（aa…\n改 ）繁,, ）到 到从（aa…" },
    Case { before: "，，是文字。the这一段文字合成的 文字the是value这一段，the是，是是the。 。，the，。。the这一段thevalue。the文字， 这一段", after: "，，是文字。the这一段文字合成的 文字the是value这一段，the是，是是the。 。，the，。。the这一段theva到bb到从\n）文字， 这一段", prose_length: 75, trailing: 0, flat: "，，是文字。the这一段文字合成的 文字the是value这一段，the是，是是the。 。，the，。。the这一段thevalue。the文字， 这一段", folded: ",,是文字.the这一段文字合成的文字the是value这一段,the是,是是the..,the,..the这一段thevalue.the文字,这一段", opcodes: "equal:0:64:0:64 replace:64:71:64:71 equal:71:78:71:78", changes: "原 …he这一段thevalue。the文字， 这一段\n改 …he这一段theva到bb到从 ）文字， 这一段" },
    Case { before: "简简 \na,从,己从繁a己从己。。简ba己简）丙己a）简 己 到丁丁\n己繁丙（）己（简简从,（繁b从简戊简。从a丙丁从。戊繁戊a丙a 。丙到a。（a从戊。简\n,,从己丙（ ）戊简丙戊从\n戊戊b简）到从,从\nb\n到（己）b从。到,己繁\n戊戊a 。戊己b到b从从 戊到戊,\n繁 。b。简己,,己丁（a繁简,。（繁。丁\n戊丙简丙到繁到, b戊到繁丙简  （ab到（到\n\nb己,, （,到丁aa从b。a\n己从", after: "简简 \na,从,己从繁a己从己。。简ba己简）丙己a）简 己 到丁丁\n己繁丙（）己（简简从,（繁b从简戊简。从a丙丁从。戊繁戊a丙a 。丙到a。（a从戊。简\n,,从己丙（ ）戊简丙戊从丁（,己己（到从,从\nb\n到（己）b从。到,己繁\n（）a）丙b繁。到b从从 戊到戊,\n繁 。b。简己,,己己丁（a繁简,。（繁。丁\n戊丙简丙到繁到, b,丁繁丙简  （ab到（到\n\nb己,, （,到丁aa从b。a\n己从", prose_length: 176, trailing: 0, flat: "简简 a,从,己从繁a己从己。。简ba己简）丙己a）简 己 到丁丁 己繁丙（）己（简简从,（繁b从简戊简。从a丙丁从。戊繁戊a丙a 。丙到a。（a从戊。简 ,,从己丙（ ）戊简丙戊从 戊戊b简）到从,从 b 到（己）b从。到,己繁 戊戊a 。戊己b到b从从 戊到戊, 繁 。b。简己,,己丁（a繁简,。（繁。丁 戊丙简丙到繁到, b戊到繁丙简 （ab到（到 b己,, （,到丁aa从b。a 己从", folded: "简简a,从,己从繁a己从己..简ba己简)丙己a)简己到丁丁己繁丙()己(简简从,(繁b从简戊简.从a丙丁从.戊繁戊a丙a.丙到a.(a从戊.简,,从己丙()戊简丙戊从戊戊b简)到从,从b到(己)b从.到,己繁戊戊a.戊己b到b从从戊到戊,繁.b.简己,,己丁(a繁简,.(繁.丁戊丙简丙到繁到,b戊到繁丙简(ab到(到b己,,(,到丁aa从b.a己从", opcodes: "equal:0:92:0:92 replace:92:200:92:201", changes: "原 …己丙（ ）戊简丙戊从 戊戊b简）到从,从 b 到（己）b从。到,己繁 戊戊a 。戊己b到b从从 戊到戊, 繁 。b。简己,,己丁（a繁简,。（繁。丁 戊丙简丙到繁到, b戊到繁丙简 （ab到（到 b己,, （,到丁aa从b。a 己从\n改 …己丙（ ）戊简丙戊从丁（,己己（到从,从 b 到（己）b从。到,己繁 （）a）丙b繁。到b从从 戊到戊, 繁 。b。简己,,己己丁（a繁简,。（繁。丁 戊丙简丙到繁到, b,丁繁丙简 （ab到（到 b己,, （,到丁aa从b。a 己从" },
    Case { before: "\n繁,到从b简", after: "\n ））繁）繁,到从简", prose_length: 6, trailing: 0, flat: "繁,到从b简", folded: "繁,到从b简", opcodes: "equal:0:1:0:1 insert:1:1:1:6 equal:1:5:6:10 delete:5:6:10:10 equal:6:7:10:11", changes: "原 繁,到从b简\n改 ））繁）繁,到从简" },
    Case { before: "是the合成的很短\n文字是。这一段value文字是value合成的，这一段文字。是合成的。。文字。\n 这一段。很短这一段合成的。这一段\nthe很短文字value，是，\nthethe。。\nthe很短\n合成的。。。value这一段 ，，文字文字文字是很短the\n文字value文字the", after: "是the合成的很短\n文字是。这一段value文字是value合成的，这一段文字。是合成的。。文字。\n 这一段。很短这一段合成的。这一段\nthe很短文字value，是，\nthethe。。\nthe很短\n合成的。。。value这一段 ，，文字文字文字是很短the\n文字value文字the", prose_length: 132, trailing: 0, flat: "是the合成的很短 文字是。这一段value文字是value合成的，这一段文字。是合成的。。文字。 这一段。很短这一段合成的。这一段 the很短文字value，是， thethe。。 the很短 合成的。。。value这一段 ，，文字文字文字是很短the 文字value文字the", folded: "是the合成的很短文字是.这一段value文字是value合成的,这一段文字.是合成的..文字.这一段.很短这一段合成的.这一段the很短文字value,是,thethe..the很短合成的...value这一段,,文字文字文字是很短the文字value文字the", opcodes: "equal:0:141:0:141", changes: "" },
    Case { before: "）从简\n到,,繁,简 \n 繁（,）（  繁（b aa从从简,）从\n。）从\n简\n简", after: "）从简\na）简繁,简 \n 繁（,）（ 到,（b aa从从简,）从简", prose_length: 30, trailing: 0, flat: "）从简 到,,繁,简 繁（,）（ 繁（b aa从从简,）从 。）从 简 简", folded: ")从简到,,繁,简繁(,)(繁(baa从从简,)从.)从简简", opcodes: "equal:0:4:0:4 replace:4:7:4:7 equal:7:19:7:19 replace:19:21:19:21 equal:21:32:21:32 delete:32:37:32:32 equal:37:38:32:33 delete:38:40:33:33", changes: "原 ）从简 到,,繁,简 繁（,）…\n改 ）从简 a）简繁,简 繁（,）…\n\n原 …简 繁（,）（ 繁（b aa从从简,）…\n改 …简 繁（,）（ 到,（b aa从从简,）…\n\n原 …b aa从从简,）从 。）从 简 简\n改 …b aa从从简,）从简" },
    Case { before: "", after: "a b,。", prose_length: 0, trailing: 0, flat: "", folded: "", opcodes: "insert:0:0:0:5", changes: "原 \n改 a b,。" },
    Case { before: "b繁从a到,b（繁 ,,b（繁））从\n从。a到。a（） \n繁a）b a 简到b。。\n（\n繁,,繁从）从。 ））繁\n到 a到） ）简简简b从  ,,从a（（。）a）b\n到\n, 简, , 简简。,）从）,,\n从繁从简到 a。从）到从\n从从a（（（繁\n从b到\n从。a 到ba\n繁\na繁繁\n\nb到从。从 （。a繁\nab）繁aa到\n,到繁繁 ,,a到 b（简b,\n。）繁a。a,））从简繁从到）到（\n从 ）（）。到a\n到（,aa到", after: "b繁从a到,b（繁 ,,b（繁））从\n从。a到。a（） \n繁a）b a 简到b。。\n（\n繁,,繁从）从。 ））繁\n到 a到） ）简简简b从  ,,）b\n到\n, 简, , 简简。,）从）,,\n从繁从简到 a。从）到从\n从从a（（（繁\n从b到\n从。a 到ba\n繁\na繁繁\n\nb到从。从 （。a繁\nab）繁aa到\n,到繁繁 ,,a到 b（简b,\n。）繁,））从简繁从到）到（\n从 \n到（,aa到", prose_length: 172, trailing: 0, flat: "b繁从a到,b（繁 ,,b（繁））从 从。a到。a（） 繁a）b a 简到b。。 （ 繁,,繁从）从。 ））繁 到 a到） ）简简简b从 ,,从a（（。）a）b 到 , 简, , 简简。,）从）,, 从繁从简到 a。从）到从 从从a（（（繁 从b到 从。a 到ba 繁 a繁繁 b到从。从 （。a繁 ab）繁aa到 ,到繁繁 ,,a到 b（简b, 。）繁a。a,））从简繁从到）到（ 从 ）（）。到a 到（,aa到", folded: "b繁从a到,b(繁,,b(繁))从从.a到.a()繁a)ba简到b..(繁,,繁从)从.))繁到a到))简简简b从,,从a((.)a)b到,简,,简简.,)从),,从繁从简到a.从)到从从从a(((繁从b到从.a到ba繁a繁繁b到从.从(.a繁ab)繁aa到,到繁繁,,a到b(简b,.)繁a.a,))从简繁从到)到(从)().到a到(,aa到", opcodes: "equal:0:73:0:73 delete:73:80:73:73 equal:80:180:73:173 delete:180:183:173:173 equal:183:197:173:187 delete:197:203:187:187 equal:203:210:187:194", changes: "原 …）简简简b从 ,,从a（（。）a）b 到 , 简, …\n改 …）简简简b从 ,,）b 到 , 简, …\n\n原 … b（简b, 。）繁a。a,））从简繁从到）到…\n改 … b（简b, 。）繁,））从简繁从到）到…\n\n原 …简繁从到）到（ 从 ）（）。到a 到（,aa到\n改 …简繁从到）到（ 从 到（,aa到" },
    Case { before: "bb,。简\n ba（ 简 （简。简\n（到a。到（a（从到 a繁（。（\n繁。 。\n", after: "bb,））a。简\n ba（ 简 （简。简\n（到a。到（a（从到 a繁（。（\n繁。 。\n", prose_length: 31, trailing: 1, flat: "bb,。简 ba（ 简 （简。简 （到a。到（a（从到 a繁（。（ 繁。 。", folded: "bb,.简ba(简(简.简(到a.到(a(从到a繁(.(繁..", opcodes: "equal:0:3:0:3 insert:3:3:3:6 equal:3:40:6:43", changes: "原 bb,。简 ba（ 简 …\n改 bb,））a。简 ba（ 简 …" },
    Case { before: "a到b（简 从到简b简丙）\n戊）（丙戊ba丁繁 a丁b 丙b,己到从）繁）, 丁, bb）繁）,）丙,到简（繁,到,到。己从繁,（戊）（到,简戊戊己到丁丙）b丙）丁到简丁到繁己丁 戊 （b己到） 戊（（己简。（简从到丙a丙简简繁\n己 繁己,", after: "a到b（简 从到简b简丙）\n戊）（丙戊ba丁繁 a丁b 丙b,己到从）繁）, 丁, bb）繁）,）丙,到简（繁,到,到。己从繁,（戊）（到,简戊戊己到丁丙）b丙）丁到简丁到繁己丁 戊 （b己到） 戊（（己简。（简从到丙a丙简简繁\n己 繁己,", prose_length: 109, trailing: 0, flat: "a到b（简 从到简b简丙） 戊）（丙戊ba丁繁 a丁b 丙b,己到从）繁）, 丁, bb）繁）,）丙,到简（繁,到,到。己从繁,（戊）（到,简戊戊己到丁丙）b丙）丁到简丁到繁己丁 戊 （b己到） 戊（（己简。（简从到丙a丙简简繁 己 繁己,", folded: "a到b(简从到简b简丙)戊)(丙戊ba丁繁a丁b丙b,己到从)繁),丁,bb)繁),)丙,到简(繁,到,到.己从繁,(戊)(到,简戊戊己到丁丙)b丙)丁到简丁到繁己丁戊(b己到)戊((己简.(简从到丙a丙简简繁己繁己,", opcodes: "equal:0:120:0:120", changes: "" },
    Case { before: "a丙", after: "", prose_length: 2, trailing: 0, flat: "a丙", folded: "a丙", opcodes: "delete:0:2:0:0", changes: "原 a丙\n改" },
    Case { before: "文字", after: "文a繁从从从aa到 ） 从", prose_length: 2, trailing: 0, flat: "文字", folded: "文字", opcodes: "equal:0:1:0:1 replace:1:2:1:13", changes: "原 文字\n改 文a繁从从从aa到 ） 从" },
    Case { before: "。\n。。很短value是。很短 这一段\n。  。文字是这一段\nvalue文字是，文字，\n很短the\n很短。。\nvaluevalue合成的，value很短thevalue是value是 the，合成的是，这一段是。\n合成的\n这一段很短这一段value合成的合成的是，是the很短合成的合成的 ，合成的，是。文字 \n，这一段\n。很短\n很短", after: "。\n。。很短value是。很短 这一到到（到段\n。  。文字是这一段\nvalue文字是，文字，\n很短the\n很短。。\nvaluevalue合成的，value很短thevalue是value是 the，合成的是，这一段是。\n合成的\n这一段很短这一段value合成的合成的是，是the很短合成的合成的 ，合成的，是。文字 \n，这一段\n。很短\n很短", prose_length: 150, trailing: 0, flat: "。 。。很短value是。很短 这一段 。 。文字是这一段 value文字是，文字， 很短the 很短。。 valuevalue合成的，value很短thevalue是value是 the，合成的是，这一段是。 合成的 这一段很短这一段value合成的合成的是，是the很短合成的合成的 ，合成的，是。文字 ，这一段 。很短 很短", folded: "...很短value是.很短这一段..文字是这一段value文字是,文字,很短the很短..valuevalue合成的,value很短thevalue是value是the,合成的是,这一段是.合成的这一段很短这一段value合成的合成的是,是the很短合成的合成的,合成的,是.文字,这一段.很短很短", opcodes: "equal:0:18:0:18 insert:18:18:18:22 equal:18:167:22:171", changes: "原 …lue是。很短 这一段 。 。文字是这…\n改 …lue是。很短 这一到到（到段 。 。文字是这…" },
    Case { before: "\nthe合成的是很短 合成的很短，value合成的 the很短这一段是合成的很短。是the很短这一段 文字。value这一段\n很短value这一段合成的value，合成的文字。valuevalue", after: "\nthe合成的是很短 合成的很短，value合成的 the很短这一段是合成的很短。是the很短这一段 文字。value这一段\n很短value这一段合成的value，合成的文字。valueva", prose_length: 93, trailing: 0, flat: "the合成的是很短 合成的很短，value合成的 the很短这一段是合成的很短。是the很短这一段 文字。value这一段 很短value这一段合成的value，合成的文字。valuevalue", folded: "the合成的是很短合成的很短,value合成的the很短这一段是合成的很短.是the很短这一段文字.value这一段很短value这一段合成的value,合成的文字.valuevalue", opcodes: "equal:0:95:0:95 delete:95:98:95:95", changes: "原 …文字。valuevalue\n改 …文字。valueva" },
];
