"""Generate the parity corpus the Rust hook renderer is checked against.

``rust/hook/render.rs`` reimplements the counting and diff display of
``src/limae/hook.py``, whose alignment is ``difflib.SequenceMatcher``.
A reimplementation of a diff is not judged by looking reasonable: two
reasonable diffs of the same rewrite disagree about how many changes it
made, and the count is on the user's screen. So the reference
implementation is run here over a fixed corpus and its answers are
written out; the Rust test replays them and fails when the port and the
reference part ways.

The corpus is synthetic and deterministic: a fixed seed, a small
alphabet (repetition is what makes alignment ties and ``autojunk``
pruning bite), and lengths that straddle the 200-element threshold
``difflib`` starts pruning at.

Usage::

  python tools/render_diff_cases.py            # rewrite the corpus
  python tools/render_diff_cases.py --check    # fail if it would change
  python tools/render_diff_cases.py --count 20000 --stdout > cases.rs

The corpus is written as Rust source rather than as data beside it: the
Cargo package carries ``rust/**/*.rs`` and nothing else, so a corpus in
any other shape would compile here and be missing from the package the
distribution gate unpacks.
"""

import argparse
import difflib
import pathlib
import random
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "src"))

from limae import hook  # noqa: E402

CORPUS = (
    pathlib.Path(__file__).resolve().parent.parent
    / "rust"
    / "hook"
    / "render_cases.rs"
)
HEADER = """// Generated by tools/render_diff_cases.py; do not edit by hand.
//
// What `src/limae/hook.py` answers over a fixed synthetic corpus, replayed by
// `render_tests.rs` against this module's port of it. Regenerate with
// `python tools/render_diff_cases.py` and check with `--check`.

/// One before/after pair and the reference implementation's answers for it.
struct Case {
    before: &'static str,
    after: &'static str,
    prose_length: usize,
    trailing: usize,
    flat: &'static str,
    folded: &'static str,
    /// The opcodes as `tag:i1:i2:j1:j2`, separated by spaces.
    opcodes: &'static str,
    changes: &'static str,
}

#[rustfmt::skip]
const CASES: &[Case] = &[
"""
FOOTER = "];\n"


def _literal(text: str) -> str:
  """Return one Rust string literal spelling ``text``."""
  out = ['"']
  for character in text:
    if character in '\\"':
      out.append(f"\\{character}")
    elif character == "\n":
      out.append("\\n")
    elif character == "\r":
      out.append("\\r")
    elif character == "\t":
      out.append("\\t")
    elif ord(character) < 0x20 or ord(character) == 0x7F:
      out.append(f"\\u{{{ord(character):x}}}")
    else:
      out.append(character)
  out.append('"')
  return "".join(out)


def _case(answers: dict[str, object]) -> str:
  """Return one ``Case`` literal."""
  fields = ", ".join(
      f"{name}: {_literal(value) if isinstance(value, str) else value}"
      for name, value in answers.items()
  )
  return f"    Case {{ {fields} }},\n"


SEED = 20260907
# Small on purpose: repeated characters are what make the tie-breaks and
# the popularity pruning decide the answer.
ALPHABET = "从简到繁 a,b。（）\n"
# A second one for the cases that should read more like a message.
WORDS = (
    "这一段",
    "文字",
    "很短",
    "the",
    "value",
    "是",
    "合成的",
    "，",
    "。",
    " ",
    "\n",
)
# Fenced blocks, the other half of `prose_length`.
FENCED = "```py\nx = 1\n```\n"

HANDMADE = (
    ("", ""),
    ("", "新加的一整段"),
    ("原本就有的一段", ""),
    (
        "这里有 (注) 一处，正文继续写下去，后面还有别的话。",
        "这里有 「注」 一处，正文继续写下去，后面还有别的话。",
    ),
    (
        "这里有（注）一处，正文继续写下去，后面还有别的话。",
        "这里有(注)一处，正文继续写下去，后面还有别的话。",
    ),
    ("一二三四五六七八九十", "一二三四五六七八九十"),
    ("一二三四五六七八九十甲乙", "一二三四五六七八九十丙乙"),
    ("甲一二三四五六七八九十乙", "丙一二三四五六七八九十乙"),
    (
        "这一句里有两处要改，前面一处，后面也有一处收尾。",
        "这一句里有两处会改，前面一处，后面也有一处结尾。",
    ),
    ("紧挨着的甲乙两字", "紧挨着的丙丁两字"),
    (f"前面一段话{FENCED}后面一段话", f"前面一段话{FENCED}后面另一段话"),
    (
        "行末有空格 \n下一行\r\n第三行\x0b第四行\x1c第五行",
        "行末有空格\n下一行\r\n第三行\x0b第四行\x1c第五行",
    ),
    (
        "表情 \U0001f642 也算一个字符，后面继续写。",
        "表情 \U0001f643 也算一个字符，后面继续写。",
    ),
    ("尾巴上有换行\n\n\n", "尾巴上有换行\n"),
    ("~~~\nfenced\n~~~\n只有围栏外算数", "~~~\nfenced\n~~~\n只有围栏外的算数"),
    ("  ```不闭合的围栏\n后面全部不算", "  ```不闭合的围栏\n后面也全部不算"),
    ("空白 与 分隔符\x1f都是空白", "空白 与 分隔符\x1f也是空白"),
)


def _noisy(rng: random.Random, size: int, alphabet: str) -> str:
  """Build one synthetic text of about ``size`` characters."""
  return "".join(rng.choice(alphabet) for _ in range(size))


def _prose(rng: random.Random, words: int) -> str:
  """Build one synthetic text that looks more like a message."""
  return "".join(rng.choice(WORDS) for _ in range(words))


def _edit(rng: random.Random, text: str, edits: int, alphabet: str) -> str:
  """Return ``text`` with a few random runs replaced, inserted or cut."""
  out = list(text)
  for _ in range(edits):
    if not out:
      out = list(_noisy(rng, rng.randrange(1, 8), alphabet))
      continue
    at = rng.randrange(len(out))
    span = rng.randrange(1, min(9, len(out) - at + 1))
    kind = rng.random()
    if kind < 0.4:
      out[at : at + span] = list(_noisy(rng, span, alphabet))
    elif kind < 0.7:
      out[at:at] = list(_noisy(rng, rng.randrange(1, 6), alphabet))
    else:
      del out[at : at + span]
  return "".join(out)


def pairs(rng: random.Random, count: int) -> list[tuple[str, str]]:
  """Return the corpus's before/after pairs."""
  made = list(HANDMADE)
  sizes = [0, 1, 2, 7, 40, 120, 198, 199, 200, 201, 210, 260]
  while len(made) < count:
    size = rng.choice(sizes)
    alphabet = ALPHABET if rng.random() < 0.6 else ALPHABET + "丙丁戊己"
    before = (
        _noisy(rng, size, alphabet)
        if rng.random() < 0.6
        else _prose(rng, max(1, size // 3))
    )
    made.append((before, _edit(rng, before, rng.randrange(0, 5), alphabet)))
  return made[:count]


def answers(before: str, after: str) -> dict[str, object]:
  """Run the reference implementation over one pair."""
  ops = difflib.SequenceMatcher(None, before, after).get_opcodes()
  return {
      "before": before,
      "after": after,
      "prose_length": hook.prose_length(before),
      "trailing": hook._trailing(before),
      "flat": hook._flat(before),
      "folded": hook._folded(before),
      "opcodes": " ".join("{}:{}:{}:{}:{}".format(*op) for op in ops),
      "changes": hook._changes(before, after),
  }


def corpus(count: int) -> list[dict[str, object]]:
  """Return the whole corpus, answers included."""
  rng = random.Random(SEED)
  return [answers(before, after) for before, after in pairs(rng, count)]


def main(argv: list[str]) -> int:
  """Write, check or print the corpus."""
  parser = argparse.ArgumentParser(description=__doc__)
  _ = parser.add_argument("--count", type=int, default=90)
  _ = parser.add_argument("--check", action="store_true")
  _ = parser.add_argument("--stdout", action="store_true")
  args = parser.parse_args(argv)
  text = HEADER + "".join(_case(case) for case in corpus(args.count)) + FOOTER
  if args.stdout:
    _ = sys.stdout.write(text)
    return 0
  if args.check:
    if CORPUS.read_text(encoding="utf-8") != text:
      _ = sys.stderr.write(f"{CORPUS} is out of date\n")
      return 1
    return 0
  _ = CORPUS.write_text(text, encoding="utf-8")
  return 0


if __name__ == "__main__":
  raise SystemExit(main(sys.argv[1:]))
