#!/usr/bin/env bash
# Renders the Homebrew formula for one Release tag.
#
#   tools/render_homebrew_formula.sh v0.13.2 <assets-dir> <out-file>
#
# <assets-dir> is a directory holding the Release's `limae-<target>.sha256`
# sidecars (what `gh release download --pattern 'limae-*'` leaves behind).
# Only the sidecars are read: the formula points Homebrew at the Release URLs
# and hands it the digests, and Homebrew does the downloading and checking.
#
# Everything that varies between releases is the version and the four
# digests. Everything else is the template below — so the thing to review is
# this file, once, rather than a generated formula on every release.
set -euo pipefail

if [ "$#" -ne 3 ]; then
  echo "usage: $0 <tag> <assets-dir> <out-file>" >&2
  exit 2
fi

tag="$1"
assets="$2"
out="$3"

# The tag is pasted into four download URLs and into `version`, so it is
# asserted to be a tag rather than trusted to be one.
if [[ ! $tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "$0: \`$tag\` is not a v<major>.<minor>.<patch> tag" >&2
  exit 1
fi
version="${tag#v}"

# Reads one sidecar and returns its digest, having checked that it is one.
# A missing or malformed sidecar stops the run here; the alternative is a
# formula carrying an empty `sha256 ""`, which fails much later and in
# someone else's terminal.
digest() {
  local target="$1" file value
  file="$assets/limae-$target.sha256"
  [ -f "$file" ] || {
    echo "$0: no sidecar at $file" >&2
    exit 1
  }
  value="$(cut -d' ' -f1 <"$file")"
  [ "${#value}" -eq 64 ] || {
    echo "$0: $file does not hold a sha256 digest" >&2
    exit 1
  }
  printf '%s' "$value"
}

darwin_arm="$(digest aarch64-apple-darwin)"
darwin_intel="$(digest x86_64-apple-darwin)"
linux_arm="$(digest aarch64-unknown-linux-musl)"
linux_intel="$(digest x86_64-unknown-linux-musl)"

base="https://github.com/Luolc/limae/releases/download/$tag"

# `desc` is not taken from Cargo.toml on purpose: Homebrew's audit caps it at
# 80 characters and rejects a leading article, and the crate's description is
# 150 characters beginning with "A". Two audiences, two sentences.
#
# The `test do` block has both arms. A clean file has to pass and a file that
# breaks a default rule has to come back non-zero and name the rule — a test
# that only ran `--help` would pass just as well for a binary that lints
# nothing, and `brew test` would then be a switch that is always green.
cat >"$out" <<FORMULA
# Generated by tools/render_homebrew_formula.sh in Luolc/limae. Edits here are
# overwritten by the next release; change the template in that repository.
class Limae < Formula
  desc "Markdown linter for Chinese technical-writing typography"
  homepage "https://github.com/Luolc/limae"
  version "$version"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$base/limae-aarch64-apple-darwin.tar.gz"
      sha256 "$darwin_arm"
    end
    on_intel do
      url "$base/limae-x86_64-apple-darwin.tar.gz"
      sha256 "$darwin_intel"
    end
  end

  on_linux do
    on_arm do
      url "$base/limae-aarch64-unknown-linux-musl.tar.gz"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$base/limae-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$linux_intel"
    end
  end

  def install
    bin.install "limae"
  end

  test do
    (testpath/"clean.md").write("中文 abc 混排。\n")
    system bin/"limae", "clean.md"

    (testpath/"bad.md").write("中文abc混排。\n")
    assert_match "zh-typography-4", shell_output("#{bin}/limae bad.md", 1)
  end
end
FORMULA

# Positive assertion on what was written, not on what was intended: four
# distinct digests and four URLs carrying this tag have to be in the file.
count="$(grep -c '^      sha256 "' "$out")"
[ "$count" -eq 4 ] || {
  echo "$0: expected 4 sha256 lines in $out, found $count" >&2
  exit 1
}
count="$(grep -c "releases/download/$tag/limae-" "$out")"
[ "$count" -eq 4 ] || {
  echo "$0: expected 4 $tag download URLs in $out, found $count" >&2
  exit 1
}
echo "rendered $out for $tag"
